### ISSUE TITLE
Error during conversion of a PaddleOCR model to ONNX 

### ISSUE THREAD

**Issue by djalusic** [PaddlePaddle/Paddle2ONNX#1028]
Hello, I'm using paddle2onnx-1.0.5 with python>=3.6, paddlepaddle>=2.0.0 on macOS with M1 chip. 

I want to convert _latin_PP-OCRv3_rec_ model downloaded from [the model zoo](https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.6/doc/doc_en/models_list_en.md).

```
paddle2onnx --model_dir latin_PP-OCRv3_rec_infer \
--model_filename inference.pdmodel \
--save_file latin.onnx
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: /Users/drajsel/Downloads/latin_PP-OCRv3_rec_infer/inference.pdmodel
[Paddle2ONNX] Paramters file path:
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Use opset_version = 9 for ONNX export.
Traceback (most recent call last):
  File "/Users/drajsel/.pyenv/versions/paddle2onxx/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/Users/drajsel/.pyenv/versions/paddle2onxx/lib/python3.9/site-packages/paddle2onnx/command.py", line 233, in main
    c_paddle_to_onnx(
  File "/Users/drajsel/.pyenv/versions/paddle2onxx/lib/python3.9/site-packages/paddle2onnx/command.py", line 143, in c_paddle_to_onnx
    onnx_model_str = c_p2o.export(
IndexError: Input conv2d_0.w_0 is undefined!
```

I haven't seen any issue with this error so far. Is it possible to convert PP-OCRv3 models to ONNX?

**Comment by yeliang2258** [comment]
Hello, you did not specify the path of the weight file, please specify the path of the weight file

**Comment by djalusic** [comment]
Thank you for clarification. From the help I understood it's optional if I set model directory. 
```
 PaddlePaddle model's param file name(param files combined in single file), which under directory seted by
                        --model_dir
```
