### ISSUE TITLE
ModuleNotFoundError: No module named 'paddle2onnx.version'

### ISSUE THREAD

**Issue by ly19940318** [PaddlePaddle/Paddle2ONNX#1074]
使用命令将输入改为静态shape
python -m paddle2onnx.optimize --input_model model.onnx \
                               --output_model new_model.onnx \
                               --input_shape_dict "{'x':[1,3,224,224]}"

**问题描述**
Traceback (most recent call last):
  File "D:\Anaconda\Anaconda\envs\paddle-2.4.1\lib\runpy.py", line 188, in _run_module_as_main
    mod_name, mod_spec, code = _get_module_details(mod_name, _Error)
  File "D:\Anaconda\Anaconda\envs\paddle-2.4.1\lib\runpy.py", line 111, in _get_module_details
    __import__(pkg_name)
  File "D:\python-code\10.Paddle2ONNX-develop\paddle2onnx\__init__.py", line 19, in <module>
    from .version import version
ModuleNotFoundError: No module named 'paddle2onnx.version'

版本：
paddle2onnx 1.0.6
onnx 1.13.0

**Comment by Zheng-Bicheng** [comment]
退出Paddle2ONNX文件夹再用这个命令哈

**Comment by ly19940318** [comment]
> 退出Paddle2ONNX文件夹再用这个命令哈

谢谢老师！转换成功了。

**Comment by L0LIPPOP** [comment]
原来如此我也解决了
