### ISSUE TITLE
使用pip安装报不能找到cmake

### ISSUE THREAD

**Issue by yuanrui** [PaddlePaddle/Paddle2ONNX#1119]
**问题描述**
使用pip安装报不能找到cmake，出现这个报错后，本地安装了cmake，再次安装还是报错。
```
C:\Windows\system32>pip install paddle2onnx
Collecting paddle2onnx
  Using cached paddle2onnx-0.9.2-py3-none-any.whl (100 kB)
Requirement already satisfied: six in c:\python311\lib\site-packages (from paddle2onnx) (1.16.0)
Requirement already satisfied: protobuf in c:\python311\lib\site-packages (from paddle2onnx) (4.23.2)
Collecting onnx<=1.9.0 (from paddle2onnx)
  Using cached onnx-1.9.0.tar.gz (9.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... error
  error: subprocess-exited-with-error

  × Getting requirements to build wheel did not run successfully.
  │ exit code: 1
  ╰─> [22 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      Traceback (most recent call last):
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 118, in get_requires_for_build_wheel
          return hook(config_settings)
                 ^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-xq1prqrd\overlay\Lib\site-packages\setuptools\build_meta.py", line 341, in get_requires_for_build_wheel
          return self._get_build_requires(config_settings, requirements=['wheel'])
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-xq1prqrd\overlay\Lib\site-packages\setuptools\build_meta.py", line 323, in _get_build_requires
          self.run_setup()
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-xq1prqrd\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-xq1prqrd\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 86, in <module>
      AssertionError: Could not find "cmake" executable!
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error

× Getting requirements to build wheel did not run successfully.
│ exit code: 1
╰─> See above for output.

note: This error originates from a subprocess, and is likely not a problem with pip.

```

**更多信息 :**

处理器	Intel(R) Core(TM) i5-6500 CPU @ 3.20GHz   3.20 GHz
机带 RAM	16.0 GB
系统类型	64 位操作系统, 基于 x64 的处理器

版本	Windows 11 专业版
版本	21H2
安装日期	‎2021/‎12/‎22
操作系统版本	22000.1936
体验	Windows 功能体验包 1000.22001.1000.0
Python 3.11.0 (main, Oct 24 2022, 18:26:48) [MSC v.1933 64 bit (AMD64)] on win32

**报错截图**

![image](https://github.com/PaddlePaddle/Paddle2ONNX/assets/3859838/e857ea2d-c7ea-4738-8170-6d95b616ec44)

**Comment by yuanrui** [comment]
重启电脑后，重新运行命令行报另外的错误。
```
C:\Windows\system32>pip install paddle2onnx
Collecting paddle2onnx
  Using cached paddle2onnx-0.9.2-py3-none-any.whl (100 kB)
Requirement already satisfied: six in c:\python311\lib\site-packages (from paddle2onnx) (1.16.0)
Requirement already satisfied: protobuf in c:\python311\lib\site-packages (from paddle2onnx) (4.23.2)
Collecting onnx<=1.9.0 (from paddle2onnx)
  Using cached onnx-1.9.0.tar.gz (9.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Installing backend dependencies ... done
  Preparing metadata (pyproject.toml) ... done
Requirement already satisfied: numpy>=1.16.6 in c:\python311\lib\site-packages (from onnx<=1.9.0->paddle2onnx) (1.24.3)
Requirement already satisfied: typing-extensions>=3.6.2.1 in c:\python311\lib\site-packages (from onnx<=1.9.0->paddle2onnx) (4.6.2)
Building wheels for collected packages: onnx
  Building wheel for onnx (pyproject.toml) ... error
  error: subprocess-exited-with-error

  × Building wheel for onnx (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [121 lines of output]
      fatal: not a git repository (or any of the parent directories): .git
      C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\dist.py:755: SetuptoolsDeprecationWarning: Invalid dash-separated options
      !!

              ********************************************************************************
              Usage of dash-separated 'license-file' will not be supported in future
              versions. Please use the underscore name 'license_file' instead.

              By 2023-Sep-26, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        opt = self.warn_dash_deprecation(opt, section)
      C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\config\setupcfg.py:293: _DeprecatedConfig: Deprecated config in `setup.cfg`
      !!

              ********************************************************************************
              The license_file parameter is deprecated, use license_files instead.

              By 2023-Oct-30, you need to update your project and remove deprecated calls
              or your builds will no longer be supported.

              See https://setuptools.pypa.io/en/latest/userguide/declarative_config.html for details.
              ********************************************************************************

      !!
        parsed = self.parsers.get(option_name, lambda x: x)(value)
      running bdist_wheel
      running build
      running build_py
      running create_version
      running cmake_build
      Using cmake args: ['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Python311\\include', '-DPYTHON_EXECUTABLE=C:\\Python311\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp311-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.11', '-DONNX_USE_MSVC_STATIC_RUNTIME=ON', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\YuanRui\\AppData\\Local\\Temp\\pip-install-7fflapws\\onnx_70db1ad21a024207a167dc9f305c9452']
      -- Building for: Visual Studio 16 2019
      -- Selecting Windows SDK version 10.0.19041.0 to target Windows 10.0.22000.
      -- The C compiler identification is MSVC 19.29.30148.0
      -- The CXX compiler identification is MSVC 19.29.30148.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2019/BuildTools/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      -- Found PythonInterp: C:/Python311/python.exe (found suitable version "3.11", minimum required is "3.11")
      -- Found PythonLibs: C:/Python311/libs/python311.lib (found suitable version "3.11.0", minimum required is "3.11")
      Generated: C:/Users/YuanRui/AppData/Local/Temp/pip-install-7fflapws/onnx_70db1ad21a024207a167dc9f305c9452/.setuptools-cmake-build/onnx/onnx-ml.proto
      CMake Error at CMakeLists.txt:292 (message):
        Protobuf compiler not found
      Call Stack (most recent call first):
        CMakeLists.txt:323 (relative_protobuf_generate_cpp)


      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 353, in <module>
          main()
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 335, in main
          json_out['return_val'] = hook(**hook_input['kwargs'])
                                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Python311\Lib\site-packages\pip\_vendor\pyproject_hooks\_in_process\_in_process.py", line 251, in build_wheel
          return _build_backend().build_wheel(wheel_directory, config_settings,
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\build_meta.py", line 416, in build_wheel
          return self._build_with_temp_dir(['bdist_wheel'], '.whl',
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\build_meta.py", line 401, in _build_with_temp_dir
          self.run_setup()
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\build_meta.py", line 488, in run_setup
          self).run_setup(setup_script=setup_script)
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\build_meta.py", line 338, in run_setup
          exec(code, locals())
        File "<string>", line 337, in <module>
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\__init__.py", line 107, in setup
          return distutils.core.setup(**attrs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 185, in setup
          return run_commands(dist)
                 ^^^^^^^^^^^^^^^^^^
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\core.py", line 201, in run_commands
          dist.run_commands()
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 969, in run_commands
          self.run_command(cmd)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\wheel\bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\command\build.py", line 131, in run
          self.run_command(cmd_name)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 233, in run
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\cmd.py", line 318, in run_command
          self.distribution.run_command(command)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\dist.py", line 1244, in run_command
          super().run_command(command)
        File "C:\Users\YuanRui\AppData\Local\Temp\pip-build-env-j7b8o4ym\overlay\Lib\site-packages\setuptools\_distutils\dist.py", line 988, in run_command
          cmd_obj.run()
        File "<string>", line 219, in run
        File "C:\Python311\Lib\subprocess.py", line 413, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['C:\\Program Files\\CMake\\bin\\cmake.exe', '-DPYTHON_INCLUDE_DIR=C:\\Python311\\include', '-DPYTHON_EXECUTABLE=C:\\Python311\\python.exe', '-DBUILD_ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=onnx', '-DPY_EXT_SUFFIX=.cp311-win_amd64.pyd', '-DCMAKE_BUILD_TYPE=Release', '-DPY_VERSION=3.11', '-DONNX_USE_MSVC_STATIC_RUNTIME=ON', '-A', 'x64', '-T', 'host=x64', '-DONNX_ML=1', 'C:\\Users\\YuanRui\\AppData\\Local\\Temp\\pip-install-7fflapws\\onnx_70db1ad21a024207a167dc9f305c9452']' returned non-zero exit status 1.
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for onnx
Failed to build onnx
ERROR: Could not build wheels for onnx, which is required to install pyproject.toml-based projects
```

**Comment by baominghelly** [comment]
我用的python3.11遇到了跟你一样的问题，我重新下载了Anaconda（Python3.9），安装没有碰到任何问题。不知道对你有没有帮助

**Comment by yuanrui** [comment]
@baominghelly thanks. 估计是环境问题了。
