### ISSUE TITLE
转模型一直失败，使用的是PaddleDetectionV1.6，转的是yolov3模型，测试过yolov3_darknet_voc和yolov3_mobilenet_v1_voc

### ISSUE THREAD

**Issue by wssywh** [PaddlePaddle/Paddle2ONNX#116]
错误信息：
------------------------------------------------
load the model parameter done.
The operator sets to run test case.
{'yolo_box', 'concat', 'nearest_interp', 'multiclass_nms', 'leaky_relu', 'scale', 'elementwise_add', 'batch_norm', 'conv2d', 'transpose2'}
Traceback (most recent call last):
  File "d:\users\administrator\anaconda3\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\administrator\anaconda3\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Users\Administrator\Anaconda3\Scripts\paddle2onnx.exe\__main__.py", line 9, in <module>
  File "d:\users\administrator\anaconda3\lib\site-packages\fluid_onnx\fluid_to_onnx.py", line 230, in main
    convert(args)
  File "d:\users\administrator\anaconda3\lib\site-packages\fluid_onnx\fluid_to_onnx.py", line 194, in convert
    checker.check_model(onnx_model)
  File "d:\users\administrator\anaconda3\lib\site-packages\onnx\checker.py", line 91, in check_model
    C.check_model(model.SerializeToString())
onnx.onnx_cpp2py_export.checker.ValidationError: Node () has input size 0 not in range [min=1, max=1].

==> Context: Bad node spec: output: "nearest_interp_0.tmp_0@out_size_f" op_type: "Cast" attribute { name: "to" i: 1 type: INT }

使用export_model.py导出模型的时候没有问题，检测模型是直接从这里下载的
![image](https://user-images.githubusercontent.com/19625405/77242638-80eb5c80-6c3b-11ea-9fab-c971d6df53ea.png)
输出为：
2020-03-22 12:41:41,083-INFO: Loading parameters from output/yolov3_mobilenet_v1_voc...
2020-03-22 12:41:41,084-WARNING: output/yolov3_mobilenet_v1_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-22 12:41:41,084-WARNING: output/yolov3_mobilenet_v1_voc.pdparams not found, try to load model file saved with [ save_params, save_persistables, save_vars ]
2020-03-22 12:41:41,457-INFO: save_inference_model pruned unused feed variables im_id
2020-03-22 12:41:41,457-INFO: Export inference model to ./output\yolov3_mobilenet_v1_voc, input: ['image', 'im_size'], output: ['multiclass_nms_0.tmp_0']...
将导出后的模型转onnx的时候就一直失败，测试过最新的PaddleDetection和V1.6版本，都会出现相同的错误

**Comment by wawltor** [comment]
嗯嗯 好的 我这边来看看问题

**Comment by JerryDeepl** [comment]
> 嗯嗯 好的 我这边来看看问题

请问下，这问题有解决方案吗
