### ISSUE TITLE
（已经在issues里找过一圈答案了没有解决）faster_rcnn 转onnx 提示there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2

### ISSUE THREAD

**Issue by zhjian831129** [PaddlePaddle/Paddle2ONNX#1168]
请各位大佬看一下
1. 在AI studio平台上操作  BML codelab
2. 环境 PaddlePaddle 2.4.0     python=3.7.4
3. Paddledetection 2.5.0
4. paddle2onnx-1.1.0  （从1.0.0   1.0.6    1.1.0， 三个版本都试过，还是提示如下错误）
5. --opset_version 16 （从11改到16 都试过，还是提示如下错误）
6. 已经在export_model时， faster_rcnn/faster_rcnn_r34_fpn_1x_coco.yml里添加了export_onnx: True。
7. 该错误是在--enable_dev_version 设为True时候出现， 设为False 直接提示 找不到ModuleNotFoundError: No module named 'onnx',``

以下是运行命令：
! paddle2onnx --model_dir inference_model/faster_rcnn_r34_fpn_1x_coco \
              --model_filename model.pdmodel \
              --params_filename model.pdiparams \
              --opset_version 16 \
              --enable_dev_version True \
              --save_file final.onnx \

以下是提示：
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: inference_model/faster_rcnn_r34_fpn_1x_coco/model.pdmodel
[Paddle2ONNX] Paramters file path: inference_model/faster_rcnn_r34_fpn_1x_coco/model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] Oops, there are some operators not supported yet, including distribute_fpn_proposals,generate_proposals_v2,
[ERROR] Due to the unsupported operators, the conversion is aborted.

**Comment by zhjian831129** [comment]
如下是把-enable_dev_version 设为False的提示
运行命令：
! paddle2onnx --model_dir inference_model/faster_rcnn_r34_fpn_1x_coco \
              --model_filename model.pdmodel \
              --params_filename model.pdiparams \
              --opset_version 16 \
              --enable_dev_version False \
              --save_file final.onnx \
错误提示：
2024-01-04 11:28:48 [WARNING]	[Deprecated] `paddle2onnx.command.program2onnx` will be deprecated in the future version, the recommended usage is `paddle2onnx.export`
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/command.py", line 253, in main
    auto_update_opset=args.enable_auto_update_opset)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/command.py", line 168, in program2onnx
    from paddle2onnx.legacy.command import program2onnx
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/__init__.py", line 19, in <module>
    from .convert import dygraph2onnx, program2onnx
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/convert.py", line 23, in <module>
    from paddle2onnx.legacy.graph import PaddleGraph, ONNXGraph
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/__init__.py", line 17, in <module>
    from .onnx_graph import ONNXGraph, ONNXNode
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/graph/onnx_graph.py", line 22, in <module>
    from paddle2onnx.legacy.constant import NodeDomain, PRODUCER, dtypes
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle2onnx/legacy/constant/dtypes.py", line 17, in <module>
    from onnx import helper
ModuleNotFoundError: No module named 'onnx'
