### ISSUE TITLE
请问一下现在是还不支持分割模型的转化吗？

### ISSUE THREAD

**Issue by ljx111** [PaddlePaddle/Paddle2ONNX#121]
我用的分割模型是deeplabv3p_mobilenet

Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 10, in <module>
    sys.exit(main())
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 230, in main
    convert(args)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 99, in convert
    ] = fluid.io.load_inference_model(args.fluid_model, exe)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1193, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 742, in load_persistables
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 608, in load_vars
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 645, in load_vars
    executor.run(load_prog)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 650, in run
    use_program_cache=use_program_cache)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/executor.py", line 748, in _run
    exe.run(program.desc, scope, 0, True, True, fetch_var_name)
paddle.fluid.core_avx.EnforceNotMet: Invoke operator load error.
Python Callstacks: 
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/framework.py", line 1748, in append_op
    attrs=kwargs.get("attrs", None))
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 630, in load_vars
    'file_path': os.path.join(load_dirname, new_var.name)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 608, in load_vars
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 742, in load_persistables
    filename=filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/io.py", line 1193, in load_inference_model
    load_persistables(executor, load_dirname, program, params_filename)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 99, in convert
    ] = fluid.io.load_inference_model(args.fluid_model, exe)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/fluid_onnx/fluid_to_onnx.py", line 230, in main
    convert(args)
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 10, in <module>
    sys.exit(main())
C++ Callstacks: 
Cannot open file /home/aistudio/freeze_model/conv4_2_expand_weights for load op at [/paddle/paddle/fluid/operators/load_op.h:37]

**Comment by jiangjiajun** [comment]
目前还不支持DeepLab模型的转换
