### ISSUE TITLE
paddleocr模型转onnx

### ISSUE THREAD

**Issue by amandazw** [PaddlePaddle/Paddle2ONNX#124]
load the model parameter done.
Traceback (most recent call last):
  File "D:/work/video/beauty_ocr_sdk/paddle2onnx-develop/paddle2onnx-develop/fluid_onnx/fluid_to_onnx.py", line 235, in <module>
    main()
  File "D:/work/video/beauty_ocr_sdk/paddle2onnx-develop/paddle2onnx-develop/fluid_onnx/fluid_to_onnx.py", line 231, in main
    convert(args)
  File "D:/work/video/beauty_ocr_sdk/paddle2onnx-develop/paddle2onnx-develop/fluid_onnx/fluid_to_onnx.py", line 141, in convert
    node_proto = ops.node_maker[str(op.type)](op, block)
TypeError: 'str' object is not callable

请问这是什么问题呢？

**Comment by amandazw** [comment]
请问目前支持paddleocr转换么

**Comment by amandazw** [comment]
node_maker字典中的这句话'hard_sigmoid': 'HardSigmoid',  # Caffe2 error
造成了以下错误：
  File "D:/work/video/beauty_ocr_sdk/paddle2onnx-develop/paddle2onnx-develop/fluid_onnx/fluid_to_onnx.py", line 143, in convert
    node_proto = ops.node_maker[str(op.type)](operator=op, block=block)
TypeError: 'str' object is not callable

**Comment by jiangjiajun** [comment]
参考此说明文档 https://github.com/PaddlePaddle/paddle2onnx/blob/develop/README.md
