### ISSUE TITLE
TypeError: export() got an unexpected keyword argument 'model_file'

### ISSUE THREAD

**Issue by jiuyuedeyu156** [PaddlePaddle/Paddle2ONNX#1326]
```bash
paddle2onnx --model_dir ./ --model_filename model.pdmodel  --params_filename model.pdiparams  --save_file model.onnx
Traceback (most recent call last):
  File "/Users/liuyulong06/Workdesktop/virtual_env/base_env/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/liuyulong06/Workdesktop/virtual_env/base_env/lib/python3.12/site-packages/paddle2onnx/command.py", line 139, in main
    paddle2onnx.export(
TypeError: export() got an unexpected keyword argument 'model_file'
```

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1327
