### ISSUE TITLE
python3.8编译paddle2onnx报错

### ISSUE THREAD

**Issue by David-dotcom666** [PaddlePaddle/Paddle2ONNX#1379]
**问题描述**
请在此处详细的描述报错信息
-- Found PythonInterp: C:/Users/Administrator/AppData/Local/Temp/build-env-wzq42xyf/Scripts/python.exe (found suitable version "3.8.10", minimum required is "3.8")
-- Found Protobuf: D:/Paddle/installed_protobuf_lib/lib/libprotobuf.lib (found version "3.16.0")
-- ONNX_PROTOC_EXECUTABLE: D:/Paddle/installed_protobuf_lib/bin/protoc.exe
-- Protobuf_VERSION: 3.16.0
Generated: C:/Users/Administrator/AppData/Local/Temp/build-via-sdist-gjlj3gqi/paddle2onnx-1.2.8/.setuptools-cmake-build/third_party/onnx/onnx/onnx-ml.proto
Generated: C:/Users/Administrator/AppData/Local/Temp/build-via-sdist-gjlj3gqi/paddle2onnx-1.2.8/.setuptools-cmake-build/third_party/onnx/onnx/onnx-operators-ml.proto
Generated: C:/Users/Administrator/AppData/Local/Temp/build-via-sdist-gjlj3gqi/paddle2onnx-1.2.8/.setuptools-cmake-build/third_party/onnx/onnx/onnx-data.proto
--
-- ******** Summary ********
--   CMake version                     : 3.30.3
--   CMake command                     : C:/Users/Administrator/AppData/Local/Temp/build-env-wzq42xyf/Lib/site-packages/cmake/data/bin/cmake.exe
--   System                            : Windows
--   C++ compiler                      : C:/Program Files (x86)/Microsoft Visual Studio/2019/Community/VC/Tools/MSVC/14.29.30133/bin/Hostx64/x64/cl.exe
--   C++ compiler version              : 19.29.30148.0
--   CXX flags                         : /DWIN32 /D_WINDOWS /GR /EHsc /EHsc /wd26812
--   Build type                        : Release
--   Compile definitions               : MAX_ONNX_OPSET_VERSION=19;PADDLE2ONNX_LIB;ONNX_NAMESPACE=onnx;__STDC_FORMAT_MACROS
--   CMAKE_PREFIX_PATH                 :
--   CMAKE_INSTALL_PREFIX              : C:/Program Files/paddle2onnx
--   CMAKE_MODULE_PATH                 :
--
--   ONNX version                      : 1.16.0
--   ONNX NAMESPACE                    : onnx
--   ONNX_USE_LITE_PROTO               : OFF
--   USE_PROTOBUF_SHARED_LIBS          : OFF
--   Protobuf_USE_STATIC_LIBS          : ON
--   ONNX_DISABLE_EXCEPTIONS           : OFF
--   ONNX_DISABLE_STATIC_REGISTRATION  : OFF
--   ONNX_WERROR                       : OFF
--   ONNX_BUILD_TESTS                  : OFF
--   ONNX_BUILD_BENCHMARKS             : OFF
--   ONNX_BUILD_SHARED_LIBS            :
--   BUILD_SHARED_LIBS                 :
--
--   Protobuf compiler                 : D:/Paddle/installed_protobuf_lib/bin/protoc.exe
--   Protobuf includes                 : D:/Paddle/installed_protobuf_lib/include
--   Protobuf libraries                : D:/Paddle/installed_protobuf_lib/lib/libprotobuf.lib
--   BUILD_ONNX_PYTHON                 : OFF
------ BUILD WITH MSVC --------
-- Configuring done (2.9s)
-- Generating done (0.1s)
-- Build files have been written to: C:/Users/Administrator/AppData/Local/Temp/build-via-sdist-gjlj3gqi/paddle2onnx-1.2.8/.setuptools-cmake-build

--------------------------------------------------------------------------------------------------------------------------------------------
执行过程中报错
  tensor_util.cc
LINK : fatal error LNK1104: 无法打开文件“python38.lib” [C:\Users\Administrator\AppData\Local\Temp\build-via-sdist-gjlj3gqi\pa
ddle2onnx-1.2.8\.setuptools-cmake-build\paddle2onnx_cpp2py_export.vcxproj]
Traceback (most recent call last):
  File "D:\PY38\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 373, in <module>
    main()
  File "D:\PY38\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 357, in main
    json_out["return_val"] = hook(**hook_input["kwargs"])
  File "D:\PY38\lib\site-packages\pyproject_hooks\_in_process\_in_process.py", line 271, in build_wheel
    return _build_backend().build_wheel(
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\build_meta.py", line 421, in build_wheel
    return self._build_with_temp_dir(
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\build_meta.py", line 403, in _build_with_temp_dir
    self.run_setup()
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\build_meta.py", line 318, in run_setup
    exec(code, locals())
  File "<string>", line 191, in <module>
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\__init__.py", line 117, in setup
    return distutils.core.setup(**attrs)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\core.py", line 184, in setup
    return run_commands(dist)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\core.py", line 200, in run_commands
    dist.run_commands()
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\dist.py", line 954, in run_commands
    self.run_command(cmd)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\command\bdist_wheel.py", line 384, in run
    self.run_command("build")
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\command\build.py", line 135, in run
    self.run_command(cmd_name)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "<string>", line 148, in run
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\cmd.py", line 316, in run_command
    self.distribution.run_command(command)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\dist.py", line 950, in run_command
    super().run_command(command)
  File "C:\Users\Administrator\AppData\Local\Temp\build-env-wzq42xyf\lib\site-packages\setuptools\_distutils\dist.py", line 973, in run_command
    cmd_obj.run()
  File "<string>", line 143, in run
  File "D:\PY38\lib\subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['C:\\Users\\Administrator\\AppData\\Local\\Temp\\build-env-wzq42xyf\\Scripts\\cmake.exe', '--build', '.', '--config', 'Release', '--', '/maxcpucount:16']' returned non-zero exit status 1.

ERROR Backend subprocess exited when trying to invoke build_wheel
我尝试把python38.lib路径添加到path中还是报这个错
步骤按照
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile_local.md

**Comment by David-dotcom666** [comment]
@Zheng-Bicheng大佬麻烦帮忙看下，或者有编译好的1.2.8的whl吗?

**Comment by Zheng-Bicheng** [comment]
用WSL换linux吧，windows暂时没人力看，等测试分支的合入主分支以后，会做windows。

**Comment by David-dotcom666** [comment]
@Zheng-Bicheng  好吧，那后面再换3.0吧。软件在window开发的，整个流程都要写软件中，不能生成模型再手动转换
