### ISSUE TITLE
can't export SLANet with import error

### ISSUE THREAD

**Issue by Joker1212** [PaddlePaddle/Paddle2ONNX#1393]
my cmd is paddle2onnx --model_dir output/best_accuracy/  --model_filename inference.pdmodel --params_filename inference.pdiparams --save_file table.onnx --opset_version 16 --enable_onnx_checker True
![image](https://github.com/user-attachments/assets/8436d563-08ae-4e8d-838b-4957948b7208)
Traceback (most recent call last):
  File "/opt/conda/envs/python35-paddle120-env/bin/paddle2onnx", line 5, in <module>
    from paddle2onnx.command import main
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/__init__.py", line 17, in <module>
    from .convert import dygraph2onnx
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle2onnx/convert.py", line 16, in <module>
    import paddle
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/__init__.py", line 74, in <module>
    import paddle.distributed.fleet  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/__init__.py", line 17, in <module>
    from .spawn import spawn
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/spawn.py", line 25, in <module>
    from paddle.distributed.cloud_utils import (
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/cloud_utils.py", line 17, in <module>
    from paddle.distributed.utils.launch_utils import (
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/utils/launch_utils.py", line 25, in <module>
    from paddle.distributed.fleet.launch_utils import get_backend_by_compile_flag
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/fleet/__init__.py", line 17, in <module>
    from .base.distributed_strategy import DistributedStrategy
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/fleet/base/distributed_strategy.py", line 25, in <module>
    from paddle.distributed.fleet.utils.log_util import logger
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/fleet/utils/__init__.py", line 17, in <module>
    from . import (  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/fleet/utils/sequence_parallel_utils.py", line 22, in <module>
    from paddle.distributed.fleet.meta_parallel import get_rng_state_tracker
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/fleet/meta_parallel/__init__.py", line 27, in <module>
    from .pipeline_parallel import (  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py", line 23, in <module>
    from ..meta_optimizers.dygraph_optimizer import HybridParallelOptimizer
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/fleet/meta_optimizers/__init__.py", line 35, in <module>
    from .ps_optimizer import ParameterServerOptimizer  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/fleet/meta_optimizers/ps_optimizer.py", line 19, in <module>
    import paddle.distributed.passes
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/passes/__init__.py", line 32, in <module>
    from .pipeline_scheduler_pass import *  # noqa: F403
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/passes/pipeline_scheduler_pass/__init__.py", line 18, in <module>
    from .pipeline_1f1b import Pipeline1F1BPass  # noqa: F401
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py", line 28, in <module>
    from .pipeline_pass_base import PipelinePassBase
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_pass_base.py", line 22, in <module>
    from ..pass_utils import set_skip_gc_vars, shadow_var_between_sub_programs
ImportError: cannot import name 'shadow_var_between_sub_programs' from 'paddle.distributed.passes.pass_utils' (/opt/conda/envs/python35-paddle120-env/lib/python3.10/site-packages/paddle/distributed/passes/pass_utils.py)

**Comment by Zheng-Bicheng** [comment]
Paddle2ONNX 指定到如下版本

```bash
pip uninstall paddle2onnx
pip install paddle2onnx==1.2.5
```

Paddle 指定到 2.6.0

**Comment by Zheng-Bicheng** [comment]
已经更新支持 while 算子，等待 CI 结束后 安装 Paddle2ONNX v1.2.10 使用:

* https://github.com/PaddlePaddle/Paddle2ONNX/actions/runs/11362622694

**Comment by Zheng-Bicheng** [comment]
先关闭这个Issues，有问题请再打开并 @Zheng-Bicheng
