### ISSUE TITLE
PULC 模型转换报错

### ISSUE THREAD

**Issue by xxxyyycc** [PaddlePaddle/Paddle2ONNX#1436]
PULC 模型：https://github.com/PaddlePaddle/PaddleClas/blob/release/2.5/docs/zh_CN/models/PULC/PULC_text_image_orientation.md
报错信息如下
Traceback (most recent call last):
  File "/usr/local/python/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python/lib/python3.8/site-packages/paddle2onnx/command.py", line 145, in main
    paddle2onnx.export(
  File "/usr/local/python/lib/python3.8/site-packages/paddle2onnx/convert.py", line 41, in export
    onnx_model_str = c_p2o.export(
IndexError: Input conv2d_0.w_0 is undefined!

**Comment by Zheng-Bicheng** [comment]
是最新的 Paddle2ONNX 嘛？

**Comment by xxxyyycc** [comment]
> 是最新的 Paddle2ONNX 嘛？

<img width="756" alt="image" src="https://github.com/user-attachments/assets/436b0f8e-c57d-467a-867e-9809d640d112">

**Comment by Zheng-Bicheng** [comment]
模型发一下

**Comment by xxxyyycc** [comment]
> 模型发一下
`
import paddleclas
model = paddleclas.PaddleClas(model_name="text_image_orientation")
`
用这个代码直接下载的哈
这种方式下载应该也是一样的：
wget https://paddleclas.bj.bcebos.com/models/PULC/text_image_orientation_infer.tar && tar -xf text_image_orientation_infer.tar
