### ISSUE TITLE
paddle2onnx >= 1.2.0 转换PPOCRv4模型失败

### ISSUE THREAD

**Issue by relaxtheo** [PaddlePaddle/Paddle2ONNX#1449]
**Describe the bug**
利用paddle2onnx转换PPOCRv4模型（det和rec推理模型，由https://paddlepaddle.github.io/PaddleOCR/latest/ppocr/model_list.html下载）
paddle版本2.6.2
命令：paddle2onnx --model_dir ch_PP-OCRv4_rec_infer --model_filename inference.pdmodel --params_filename inference.pdiparams --opset_version 16 --save_file ch_PP-OCRv4_rec_infer.onnx

paddle2onnx版本1.1.0： 转换成功
paddle2onnx版本1.2.0及以上：转换失败，报错如下
  File "/home/theo/anaconda3/envs/paddleocr/bin/paddle2onnx", line 5, in <module>
    from paddle2onnx.command import main
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle2onnx/__init__.py", line 15, in <module>
    from .convert import export
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle2onnx/convert.py", line 16, in <module>
    import paddle
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/__init__.py", line 74, in <module>
    import paddle.distributed.fleet  # noqa: F401
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/__init__.py", line 17, in <module>
    from .spawn import spawn
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/spawn.py", line 25, in <module>
    from paddle.distributed.cloud_utils import (
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/cloud_utils.py", line 17, in <module>
    from paddle.distributed.utils.launch_utils import (
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/utils/launch_utils.py", line 25, in <module>
    from paddle.distributed.fleet.launch_utils import get_backend_by_compile_flag
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/fleet/__init__.py", line 17, in <module>
    from .base.distributed_strategy import DistributedStrategy
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/fleet/base/distributed_strategy.py", line 25, in <module>
    from paddle.distributed.fleet.utils.log_util import logger
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/fleet/utils/__init__.py", line 17, in <module>
    from . import (  # noqa: F401
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/fleet/utils/sequence_parallel_utils.py", line 22, in <module>
    from paddle.distributed.fleet.meta_parallel import get_rng_state_tracker
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/fleet/meta_parallel/__init__.py", line 27, in <module>
    from .pipeline_parallel import (  # noqa: F401
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/fleet/meta_parallel/pipeline_parallel.py", line 23, in <module>
    from ..meta_optimizers.dygraph_optimizer import HybridParallelOptimizer
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/fleet/meta_optimizers/__init__.py", line 35, in <module>
    from .ps_optimizer import ParameterServerOptimizer  # noqa: F401
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/fleet/meta_optimizers/ps_optimizer.py", line 19, in <module>
    import paddle.distributed.passes
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/passes/__init__.py", line 32, in <module>
    from .pipeline_scheduler_pass import *  # noqa: F403
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/passes/pipeline_scheduler_pass/__init__.py", line 18, in <module>
    from .pipeline_1f1b import Pipeline1F1BPass  # noqa: F401
  File "/home/theo/anaconda3/envs/paddleocr/lib/python3.10/site-packages/paddle/distributed/passes/pipeline_scheduler_pass/pipeline_1f1b.py", line 22, in <module>
    from ..pass_utils import (

**Comment by relaxtheo** [comment]
I tested on another PC, paddlepaddle 2.6.2+paddle2onnx 1.3.1 works, don't know where caused the problem

**Comment by Zheng-Bicheng** [comment]
<img width="1271" alt="image" src="https://github.com/user-attachments/assets/e1bee27e-4850-49c7-9adc-bd8205a368d9">

**Comment by Zheng-Bicheng** [comment]
用最新的 Paddle2ONNX

**Comment by Zheng-Bicheng** [comment]
@GreatV 大佬验证下你本地能转吗？pip可以直接下载 paddle2onnx 了

**Comment by GreatV** [comment]
![image](https://github.com/user-attachments/assets/8763092d-d133-47f8-880e-f85561393b93)
work well for me

**Comment by leduy-it** [comment]
How about this in auto compression mode:
```
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
[Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: deploy/slim/auto_compression/JPLC_v4_0212/inference.pdmodel
[Paddle2ONNX] Parameters file path: deploy/slim/auto_compression/JPLC_v4_0212/inference.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [Info] The Paddle model is a quantized model. 
[Paddle2ONNX] Oops, there are some operators not supported yet, including fake_channel_wise_dequantize_max_abs,fake_quantize_moving_average_abs_max,
[ERROR] Due to the unsupported operators, the conversion is aborted.


--------------------------------------
C++ Traceback (most recent call last):
--------------------------------------
0   paddle2onnx::Export(char const*, char const*, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*, char**, int*, char const*, bool*, bool, char**, int)

----------------------
Error Message Summary:
----------------------
FatalError: `Process abort signal` is detected by the operating system.
  [TimeInfo: *** Aborted at 1733381724 (unix time) try "date -d @1733381724" if you are using GNU date ***]
  [SignalInfo: *** SIGABRT (@0xe5) received by PID 229 (TID 0x7f37f6a31740) from PID 229 ***]

Aborted (core dumped)

```

**Comment by Zheng-Bicheng** [comment]
> How about this in auto compression mode:
> 
> ```
> grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
> [Paddle2ONNX] Start to parse PaddlePaddle model...
> [Paddle2ONNX] Model file path: deploy/slim/auto_compression/JPLC_v4_0212/inference.pdmodel
> [Paddle2ONNX] Parameters file path: deploy/slim/auto_compression/JPLC_v4_0212/inference.pdiparams
> [Paddle2ONNX] Start to parsing Paddle model...
> [Paddle2ONNX] [Info] The Paddle model is a quantized model. 
> [Paddle2ONNX] Oops, there are some operators not supported yet, including fake_channel_wise_dequantize_max_abs,fake_quantize_moving_average_abs_max,
> [ERROR] Due to the unsupported operators, the conversion is aborted.
> 
> 
> --------------------------------------
> C++ Traceback (most recent call last):
> --------------------------------------
> 0   paddle2onnx::Export(char const*, char const*, char**, int*, int, bool, bool, bool, bool, bool, paddle2onnx::CustomOp*, int, char const*, char**, int*, char const*, bool*, bool, char**, int)
> 
> ----------------------
> Error Message Summary:
> ----------------------
> FatalError: `Process abort signal` is detected by the operating system.
>   [TimeInfo: *** Aborted at 1733381724 (unix time) try "date -d @1733381724" if you are using GNU date ***]
>   [SignalInfo: *** SIGABRT (@0xe5) received by PID 229 (TID 0x7f37f6a31740) from PID 229 ***]
> 
> Aborted (core dumped)
> ```

Paddle2ONNX currently does not support the export of quantized PPOCR models.

**Comment by Zheng-Bicheng** [comment]
Perhaps you can refer to the documentation of PaddleSlim for quantization training, and then use Paddle2ONNX to export it:

* https://github.com/PaddlePaddle/PaddleSlim/tree/develop/example/auto_compression/ocr

**Comment by Zheng-Bicheng** [comment]
@leduy-it

**Comment by leduy-it** [comment]
Thanks for your reply. I realize that fp32 can export onnx so i de-quanti to fp32 then export to onnx. Easy with mode onnx_format=true in autocompression.
