### ISSUE TITLE
PaddleOCR2.0文本识别模型转换可动态输入的onnx模型报错

### ISSUE THREAD

**Issue by SWHL** [PaddlePaddle/Paddle2ONNX#177]
#### 说明
- 尝试转换PaddleOCR 2.0动态图下文本识别模型l
- 固定文本识别模型输入尺寸为(3, 32, 100),可以转换成功，
- 但是文本识别模型一般都不会固定宽的（如果固定的话，对于长文本识别会很差）

#### 转换环境：
- python 3.7
- PaddleOCR-dygraph
- Paddle2ONNX 最新版

#### 转换代码(部分)：
```python
config = load_config(FLAGS.config)
merge_config(FLAGS.opt)
logger = get_logger()
# build post process

post_process_class = build_post_process(config['PostProcess'],
                                        config['Global'])

# build model
# for rec algorithm
if hasattr(post_process_class, 'character'):
    char_num = len(getattr(post_process_class, 'character'))
    config['Architecture']["Head"]['out_channels'] = char_num
model = build_model(config['Architecture'])
print('build model...')
init_model(config, model, logger)
model.eval()

save_path = 'test.onnx'
x_spec = InputSpec([1, 3, 32, None], 'float32', 'x')  # 这里最后一维为None,想这里可以是不定的，动态输入的
paddle.onnx.export(model, save_path, input_spec=[x_spec])
```
#### 执行以上代码，报错如下：
```text
Traceback (most recent call last):
  File "export_model_onnx.py", line 49, in <module>
    main()
  File "export_model_onnx.py", line 45, in main
    paddle.onnx.export(model, save_path, input_spec=[x_spec])
  File "/home/xxxxxxx/anaconda3/envs/Paddle/lib/python3.7/site-packages/paddle/onnx/export.py", line 105, in export
    **configs)
  File "/home/xxxxxxx/anaconda3/envs/Paddle/lib/python3.7/site-packages/paddle2onnx-0.4-py3.7.egg/paddle2onnx/convert.py", line 145, in dygraph2onnx
  File "/home/xxxxxxx/anaconda3/envs/Paddle/lib/python3.7/site-packages/paddle2onnx-0.4-py3.7.egg/paddle2onnx/convert.py", line 31, in export_onnx
  File "/home/xxxxxxx/anaconda3/envs/Paddle/lib/python3.7/site-packages/paddle2onnx-0.4-py3.7.egg/paddle2onnx/graph/onnx_graph.py", line 208, in build
  File "/home/xxxxxxx/anaconda3/envs/Paddle/lib/python3.7/site-packages/paddle2onnx-0.4-py3.7.egg/paddle2onnx/graph/onnx_graph.py", line 165, in build_op_nodes
  File "/home/xxxxxxx/anaconda3/envs/Paddle/lib/python3.7/site-packages/paddle2onnx-0.4-py3.7.egg/paddle2onnx/op_mapper/op_mapper.py", line 115, in mapping
Exception: Error happened when mapping node ['pool2d@0'] to onnx, which op_type is 'pool2d' with inputs: {'X': ['relu_1.tmp_0']} and outputs: {'Out': ['pool2d_0.tmp_0']}, specific error: Converting this model to ONNX need with static input shape, please fix input shape of this model, see doc Q2 in https://github.com/PaddlePaddle/paddle2onnx/blob/develop/docs/en/FAQ.md.
```

#### 困惑：
- 根据报错信息可得，不支持动态shape，但是根据[文档](https://www.paddlepaddle.org.cn/documentation/docs/zh/develop/guides/02_paddle2.0_develop/09_model_to_onnx_cn.html)是支持动态输入的？

希望可以得到你们的解答

**Comment by Channingss** [comment]
@SWHL 
您好，由于PaddleOCR的模型存在adaptive_pool，然后ONNX不存在adaptive_pool，所以需要知道adaptive_pool输入输出的shape来计算kernel_size和stride等参数，使用ONNX中传统的pool替代，昨天我发现PaddleOCR的adaptive_pool输出shape的h,w为1，所以可以使用global_pool代替，不需要知道adaptive_pool输入输出的shape来计算kernel_size和stride等参数，这边提交代码到develop后，请使用develop分支的源码安装paddle2onnx。

关于文档中提到支持动态输入，这个不是每一个模型都支持，设计到小部分算子的转换需要用到shape哈

**Comment by WangFengtu1996** [comment]
Hi，@Channingss

在使用paddle2onnx中，如何生成固定输入大小tensor的onnx模型 ？ 因为我在jetson xavier nx 上，推理ONNX模型，仅支持固定输入。

**Comment by SWHL** [comment]
> Hi，@Channingss
> 
> 在使用paddle2onnx中，如何生成固定输入大小tensor的onnx模型 ？ 因为我在jetson xavier nx 上，推理ONNX模型，仅支持固定输入。

- 可以参考我整理的一个仓库[PaddleOCRModelConverter](https://github.com/RapidAI/PaddleOCRModelConverter)

- 具体代码如下:
https://github.com/RapidAI/PaddleOCRModelConverter/blob/37c5dff2b19263a9208373393fc3337e3d7117e8/convert_2_change_dynamic.py#L40

**Comment by WangFengtu1996** [comment]
HI, @SWHL 
十分感谢，我现在直接使用 下面这个文档中动态图的方式去完成固定输入大小。
https://aistudio.baidu.com/aistudio/projectdetail/1461212
