### ISSUE TITLE
请问怎么转换有三个model directory的PaddleOCR？

### ISSUE THREAD

**Issue by yxyphoebe** [PaddlePaddle/Paddle2ONNX#191]
现在的model是一个PaddleOCR class, 有三个model_dir，请问是要分开转换成ONNX吗？转换之后怎么combine起来，还有怎么用onnxruntime呢？

**Comment by Channingss** [comment]
@yxyphoebe 可以参考这个教程 https://aistudio.baidu.com/aistudio/projectdetail/1479970

**Comment by yxyphoebe** [comment]
好的，谢谢，照着这个tutorial做，遇到这个问题，不知道有没有人遇到过。
(1150, 720, 3)
Traceback (most recent call last):
  File "paddleocr/tools/infer/predict_system.py", line 190, in <module>
    main(utility.parse_args())
  File "paddleocr/tools/infer/predict_system.py", line 159, in main
    dt_boxes, rec_res = text_sys(img)
  File "paddleocr/tools/infer/predict_system.py", line 89, in __call__
    dt_boxes, elapse = self.text_detector(img)
  File "/Users/xinyyu/workspace/vision-service-model-deploy/ocr/ocr-mobilenet-onnx/paddleocr/tools/infer/predict_det.py", line 170, in __call__
    outputs = self.predictor.run(self.output_tensors, input_dict)
  File "/usr/local/Cellar/pyenv/1.2.7/versions/3.7.0/lib/python3.7/site-packages/onnxruntime/capi/onnxruntime_inference_collection.py", line 124, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Got invalid dimensions for input: x for the following indices
 index: 2 Got: 960 Expected: 640
 index: 3 Got: 608 Expected: 640
 Please fix either the inputs or the model.

**Comment by yxyphoebe** [comment]
请问是怎么把model 的input shape改成 -1 x 3 x -1 x -1 的
@Channingss

**Comment by Channingss** [comment]
请PaddleOCR的release/2.0分支现在支持导出为动态shape的模型： https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/tools/export_model.py
这个是导出inference模型的教程：
https://github.com/PaddlePaddle/PaddleOCR/blob/release/2.0/doc/doc_ch/inference.md

**Comment by MagicCodess** [comment]
@Channingss 请问官方提供的inference model在转换后只能输入100的宽度，这块如何修改为动态输入呢

**Comment by daixiangzi** [comment]
+1

**Comment by SWHL** [comment]
可以参考下面的代码
```python
    onnx_model = onnx.load(onnx_path)
    onnx.checker.check_model(onnx_model)
    print(f'The {onnx_path} is checked!')

    # 修改NCHW中H为动态输入
    onnx_model.graph.input[0].type.tensor_type.shape.dim[2].dim_param = '?'

    # 修改NCHW中W为动态输入
    onnx_model.graph.input[0].type.tensor_type.shape.dim[3].dim_param = '?'
    onnx.save(onnx_model, onnx_path)
```
