### ISSUE TITLE
关于对PyramidBox从paddle转成onnx的支持

### ISSUE THREAD

**Issue by fengyuentau** [PaddlePaddle/Paddle2ONNX#192]
首先非常感谢官方出的paddle2onnx的工具！

我有一个需求是要将PyramidBox转成ONNX格式进行一些Profiling，我首先尝试用Paddle2ONNX，但是报错说`depthwise_conv2d_transpose`算子还不支持。于是我就参考`nn.py`里面`Conv`的实现，把以下的代码：
https://github.com/PaddlePaddle/Paddle2ONNX/blob/5dc318a5ddf2c34245e5231266dc1797ebcc060b/paddle2onnx/op_mapper/nn.py#L58-L73

改成了
```python
@op_mapper(['conv2d_transpose', 'depthwise_conv2d_transpose'])
class ConvTranspose():
    support_opset_verison_range = (1, 12)

    @classmethod
    def opset_1(cls, graph, node, **kw):
        kernel_shape = node.input_shape('Filter', 0)
        dilations = node.attr('dilations')
        kernel_shape = kernel_shape[-2:]
        strides = node.attr('strides')
        group = node.attr('groups')
        pads = node.attr('paddings') + node.attr('paddings')
        attrs = {
            'dilations': dilations,
            'kernel_shape': kernel_shape,
            'strides': strides,
            'group': group
        }
        auto_pad = node.attr('padding_algorithm')
        if auto_pad == 'SAME':
            attrs['auto_pad'] = 'SAME_UPPER'
        elif auto_pad == 'VALID':
            attrs['auto_pad'] = 'VALID'
        else:
            attrs['pads'] = pads

        node = graph.make_node(
            'ConvTranspose',
            inputs=node.input('Input') + node.input('Filter'),
            outputs=node.output('Output'),
            attrs=attrs)
```

现在算子支持有了，但是在box_coder这里报错了：
```shell
$ paddle2onnx --model_dir ./models/PyramidBox_WiderFace --save_file pyramidbox.onnx --opset_version 12 --enable_onnx_checker True
Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 110, in mapping
    mapper_func(graph, node, **kw)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/op_mapper/detection/box_coder.py", line 44, in opset_7
    axis = int(node.attr('axis'))
TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 74, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 31, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 208, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 165, in build_op_nodes
    OpMapper.mapping(self, node)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 115, in mapping
    node.outputs) + str(e))
Exception: Error happened when mapping node ['box_coder@0'] to onnx, which op_type is 'box_coder' with inputs: {'PriorBox': ['concat_17.tmp_0'], 'PriorBoxVar': ['concat_18.tmp_0'], 'TargetBox': ['concat_13.tmp_0']} and outputs: {'OutputBox': ['box_coder_2.tmp_0']}, specific error: int() argument must be a string, a bytes-like object or a number, not 'NoneType'
```

这个错误该如何解决？我猜这个是和最后priorbox的生成和decode相关，但我这边其实可以用不到这个步骤，只需要转换出来的模型完成前向过程就可以了（输出loc和conf的特征图，decode可以自己写）。请问有什么解决办法吗？

附上PaddlePaddle/Models中face_detection（PyramidBox）提供的模型下载地址：
http://paddlemodels.bj.bcebos.com/PyramidBox_WiderFace.tar.gz

**Comment by Channingss** [comment]
@fengyuentau 看上去是paddlepaddle更新了box_coder：

  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/op_mapper/detection/box_coder.py", line 44, in opset_7
    axis = int(node.attr('axis'))

你把这一行改为：先判断一下node.attr('axis')是否为None，如果为None，指定 axis=0 试试。

**Comment by fengyuentau** [comment]
@Channingss `你好！按照你的建议改了，但现在变成在softmax节点的转换有问题了：
```shell
$ paddle2onnx --model_dir ./models/PyramidBox_WiderFace --save_file pyramidbox.onnx --opset_version 12 --enable_onnx_checker True 
Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 110, in mapping
    mapper_func(graph, node, **kw)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/op_mapper/math.py", line 383, in opset_1
    if axis < 0:
TypeError: '<' not supported between instances of 'NoneType' and 'int'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 74, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 31, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 208, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 165, in build_op_nodes
    OpMapper.mapping(self, node)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 115, in mapping
    node.outputs) + str(e))
Exception: Error happened when mapping node ['softmax@0'] to onnx, which op_type is 'softmax' with inputs: {'X': ['flatten_14.tmp_0']} and outputs: {'Out': ['softmax_0.tmp_0']}, specific error: '<' not supported between instances of 'NoneType' and 'int'
```

**Comment by Channingss** [comment]
@fengyuentau 和刚刚的问题一样，你把axis判断下是不是为None，为None的话指定axis=-1试试。

**Comment by fengyuentau** [comment]
@Channingss 谢谢你的回复。按照你的建议把axis为none的地方都修复了，但现在又碰到了这个问题：
```shell

$ paddle2onnx --model_dir ./models/PyramidBox_WiderFace --save_file pyramidbox.onnx --opset_version 12 --enable_onnx_checker True
2021-02-18 16:12:45 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-02-18 16:12:48 [INFO]      ONNX model genarated is valid.
Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/utils.py", line 43, in check_model
    onnx.checker.check_model(onnx_model)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however 'conv2d_0.tmp_1' has been used as output names multiple times.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 74, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 32, in export_onnx
    onnx_proto = onnx_graph.export_proto(enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 198, in export_proto
    check_model(onnx_proto)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/utils.py", line 45, in check_model
    raise Exception('ONNX model is not valid.')
Exception: ONNX model is not valid.
```
这个可能是要改每个node的output的名字？

**Comment by Channingss** [comment]
这里是因为paddle允许不同node的输入输出同名，但是ONNX不允许。这块的代码我们还没合入进来，今天或者明天我提交上来，到时候告知你。

**Comment by fengyuentau** [comment]
@Channingss 谢谢你！期待你的更新！

**Comment by Channingss** [comment]
@fengyuentau 请试一下这个PR的代码：https://github.com/PaddlePaddle/Paddle2ONNX/pull/183

**Comment by fengyuentau** [comment]
@Channingss 我一个一个文件的merge到了安装的包里面，但是现在batch_norm层的重名问题好像还是没有解决：
```shell
$ paddle2onnx --model_dir ./models/PyramidBox_WiderFace --save_file pyramidbox.onnx --opset_version 12 --enable_onnx_checker True
2021-02-28 15:34:05 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-02-28 15:34:08 [INFO]      ONNX model genarated is valid.
Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/utils.py", line 43, in check_model
    onnx.checker.check_model(onnx_model)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however 'batch_norm_0.tmp_2' has been used as output names multiple times.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 77, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 34, in export_onnx
    onnx_proto = onnx_graph.export_proto(enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 219, in export_proto
    check_model(onnx_proto)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/utils.py", line 45, in check_model
    raise Exception('ONNX model is not valid.')
```

**Comment by fengyuentau** [comment]
@Channingss 解决重名的是哪部分的代码？是“paddle2onnx/passes/inplace_node_pass.py”里面的这一部分吗？
```python
@PassManager('inplace_node_pass')
class InplaceNodePass(object):

    name_count = dict()

    @classmethod
    def generate_new_name(cls, name):
        if name in cls.name_count:
            cls.name_count[name] += 1
        else:
            cls.name_count[name] = 1
        new_name = name + '.' + str(cls.name_count[name])
        return new_name
```

**Comment by fengyuentau** [comment]
@Channingss 问题找到了，是跨层之间的output name是重名的，但是passmanager并没有检测这个问题，比如下面的：
```shell
BatchNormalization@22
batch_norm_22.tmp_2
Relu@56
batch_norm_22.tmp_2
```
我看看怎么改。

**Comment by Channingss** [comment]
@fengyuentau 怎么样？解决了吗

**Comment by fengyuentau** [comment]
@Channingss 昨天我把inplace_node_pass.py中的repeated_output从记录单个node改成了记录全部node的output names，但现在还是会报错，我没有很多时间去看onnx的标准，不过我猜报错的原因是只改了上个节点的输出名，但下个节点的输入名不对应。因为对当前节点我不知道怎么去追溯它的上一个节点（或许可以简单的认为跨节点重名时当前节点的上一个节点就是当前循环的i-1，但从我的观察而言这条规律并不成立），所以我昨晚就没再花时间来弄了：
```python
def get_repeated_output(inputs, outputs, repeated_output):
    # repeated_output = {}
    for idx in range(len(outputs)):
        opt = outputs[idx]
        print('\t', opt)
        if opt in inputs:
            repeated_output[opt] = idx
    return repeated_output


@PassManager('inplace_node_pass')
class InplaceNodePass(object):

    name_count = dict()

    @classmethod
    def generate_new_name(cls, name):
        if name in cls.name_count:
            cls.name_count[name] += 1
        else:
            cls.name_count[name] = 1
        new_name = name + '.' + str(cls.name_count[name])
        return new_name

    @classmethod
    def run_pass(cls, onnx_graph):
        output_to_nodes = {}
        node_map = list(onnx_graph.node_map.items())
        name_mapping = {}
        repeated_output = dict()
        for idx in range(len(node_map)):
            name, node = node_map[idx]
            print(name)
            inputs = node.inputs
            outputs = node.outputs
            for idx in range(len(inputs)):
                ipt = inputs[idx]
                if ipt in name_mapping:
                    inputs[idx] = name_mapping[ipt]
            get_repeated_output(inputs, outputs, repeated_output)
            if len(repeated_output) != 0:
                for opt, idx in repeated_output.items():
                    name_mapping[opt] = cls.generate_new_name(opt)
                    outputs[idx] = name_mapping[opt]
            node.set_inputs(inputs)
            node.set_outputs(outputs)
            onnx_graph.update_node(node)

        return onnx_graph
```

下面是报错的信息：
```shell
$ paddle2onnx --model_dir ./models/PyramidBox_WiderFace --save_file pyramidbox.onnx --opset_version 12 --enable_onnx_checker True
2021-03-01 15:22:38 [INFO]      ONNX model genarated is valid.
Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/utils.py", line 43, in check_model
    onnx.checker.check_model(onnx_model)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'Constant@1' of node: 
input: "conv2d_1.b_0" input: "Constant@1" output: "conv2d_0.tmp_1.4" name: "Reshape@1" op_type: "Reshape"
 is not output of any previous nodes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 77, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 34, in export_onnx
    onnx_proto = onnx_graph.export_proto(enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 219, in export_proto
    check_model(onnx_proto)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/utils.py", line 45, in check_model
    raise Exception('ONNX model is not valid.')
Exception: ONNX model is not valid.
```

**Comment by fengyuentau** [comment]
@Channingss 我发现我搞错了，之前打印的是未改名的。按照你的代码，跨节点的也有重新命名了，比如：
```shell
BatchNormalization@22
         before:  batch_norm_22.tmp_2
         after:  batch_norm_22.tmp_2
Relu@56
         before:  batch_norm_22.tmp_2
         after:  batch_norm_22.tmp_2.1
```
但是间隔远的节点输出没有被重新命名（看开头的BatchNormalization@20和最后一个Relu@57）：
```shell
BatchNormalization@20
         before:  batch_norm_20.tmp_2
         after:  batch_norm_20.tmp_2
Conv@71
         before:  conv2d_71.tmp_0
         after:  conv2d_71.tmp_0
BatchNormalization@21
         before:  batch_norm_21.tmp_2
         after:  batch_norm_21.tmp_2
Relu@55
         before:  batch_norm_21.tmp_2
         after:  batch_norm_21.tmp_2.1
Conv@72
         before:  conv2d_72.tmp_0
         after:  conv2d_72.tmp_0
BatchNormalization@22
         before:  batch_norm_22.tmp_2
         after:  batch_norm_22.tmp_2
Relu@56
         before:  batch_norm_22.tmp_2
         after:  batch_norm_22.tmp_2.1
Conv@73
         before:  conv2d_73.tmp_0
         after:  conv2d_73.tmp_0
BatchNormalization@23
         before:  batch_norm_23.tmp_2
         after:  batch_norm_23.tmp_2
Add@55
         before:  tmp_8
         after:  tmp_8
Relu@57
         before:  batch_norm_20.tmp_2
         after:  batch_norm_20.tmp_2
```

这是我人工找出来的，但是报错的名字并不是我找到的那个，而且这个output names在我打印出来的里面找不到：
```shell
2021-03-01 15:42:45 [INFO]      ONNX model genarated is valid.
Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/utils.py", line 43, in check_model
    onnx.checker.check_model(onnx_model)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Graph must be in single static assignment (SSA) form, however 'batch_norm_0.tmp_2' has been used as output names multiple times.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/tau/anaconda3/envs/PyramidBox/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 77, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/convert.py", line 34, in export_onnx
    onnx_proto = onnx_graph.export_proto(enable_onnx_checker)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 219, in export_proto
    check_model(onnx_proto)
  File "/home/tau/anaconda3/envs/PyramidBox/lib/python3.7/site-packages/paddle2onnx/utils.py", line 45, in check_model
    raise Exception('ONNX model is not valid.')
```

我再看看是啥问题。

**Comment by fengyuentau** [comment]
@Channingss 我知道问题是啥了。代码中判断重名的逻辑是拿一个node的input和output的对比（比如ReLU）：
```shell
Relu@25
	input before: batch_norm_1.tmp_2
	output before: batch_norm_1.tmp_2
	input after: batch_norm_1.tmp_2
	output after: batch_norm_1.tmp_2.1
```
如果有重名的就存在name_mapping中，但是模型中存在这样的情况，不同的节点的output names会存在相同的output names（比如batch_norm_0.tmp_2）：
```shell
BatchNormalization@0
	input before: conv2d_25.tmp_0
	input before: batch_norm_0.w_0
	input before: batch_norm_0.b_0
	input before: batch_norm_0.w_1
	input before: batch_norm_0.w_2
	output before: batch_norm_0.tmp_2
	input after: conv2d_25.tmp_0
	input after: batch_norm_0.w_0
	input after: batch_norm_0.b_0
	input after: batch_norm_0.w_1
	input after: batch_norm_0.w_2
	output after: batch_norm_0.tmp_2
...
Relu@27
	input before: tmp_3
	output before: batch_norm_0.tmp_2
	input after: tmp_3
	output after: batch_norm_0.tmp_2
```
这是由于存在这么一种relu，它的输入和输出不重名，但是它的输出和之前节点的输出重名了，原本的判断逻辑里面没有考虑这个，我改成下面代码就可以成功输出pyramidbox.onnx了：
```python
from paddle2onnx.passes import PassManager


def get_repeated_output(inputs, outputs):
    repeated_output = {}
    for idx in range(len(outputs)):
        opt = outputs[idx]
        if opt in inputs:
            repeated_output[opt] = idx
    return repeated_output

def print_func(src, src_name='input', stage='before'):
    for idx in range(len(src)):
        opt = src[idx]
        print('\t{} {}: {}'.format(src_name, stage, opt))

@PassManager('inplace_node_pass')
class InplaceNodePass(object):

    name_count = dict()

    @classmethod
    def generate_new_name(cls, name):
        if name in cls.name_count:
            cls.name_count[name] += 1
        else:
            cls.name_count[name] = 1
        new_name = name + '.' + str(cls.name_count[name])
        return new_name

    @classmethod
    def run_pass(cls, onnx_graph):
        output_to_nodes = {}
        node_map = list(onnx_graph.node_map.items())
        name_mapping = {}

        # repeated_output = dict()
        for idx in range(len(node_map)):
            name, node = node_map[idx]
            print(name)

            inputs = node.inputs
            # print_func(inputs, src_name='input', stage='before')
            outputs = node.outputs
            # print_func(outputs, src_name='output', stage='before')
            for idx in range(len(inputs)):
                ipt = inputs[idx]
                if ipt in name_mapping:
                    inputs[idx] = name_mapping[ipt]
            # print_func(inputs, src_name='input', stage='after')
            # 检查重名的时候不再拿inputs和outputs对比，而是name_mapping和outputs对比
            repeated_output = get_repeated_output(name_mapping, outputs)
            if len(repeated_output) != 0:
                for opt, idx in repeated_output.items():
                    name_mapping[opt] = cls.generate_new_name(opt)
                    outputs[idx] = name_mapping[opt]
            # 在name_mapping里面加入全部的output names
            for opt in outputs:
                if opt not in name_mapping:
                    name_mapping[opt] = opt
            # print_func(outputs, src_name='output', stage='after')

            node.set_inputs(inputs)
            node.set_outputs(outputs)
            onnx_graph.update_node(node)

        return onnx_graph
```

你的这个pass的PR什么时候会merge？我想把我的修改也提交为PR merge进来。
