### ISSUE TITLE
支持ultra_light_fast_generic_face_detector_1mb_640(PaddleHub)，缺少assign

### ISSUE THREAD

**Issue by Channingss** [PaddlePaddle/Paddle2ONNX#201]
Traceback (most recent call last):
  File "test_cv_module.py", line 91, in <module>
    module.export_onnx_model('output/{}.onnx'.format(module.name))
  File "/mnt/wuzewu/code/PaddleHub/paddlehub/compat/paddle_utils.py", line 220, in runner
    return func(*args, **kwargs)
  File "/mnt/wuzewu/code/PaddleHub/paddlehub/module/module.py", line 201, in export_onnx_model
    **kwargs
  File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/convert.py", line 74, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/convert.py", line 31, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 208, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 162, in build_op_nodes
    OpMapper.check_support_status(node_map, self.opset_version)
  File "/mnt/wuzewu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 1 ops are not supported yet
=========== assign ===========

**Comment by jiangjiajun** [comment]
fix here https://github.com/PaddlePaddle/Paddle2ONNX/pull/224
