### ISSUE TITLE
ONNX2TRT 输入形状为多少

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/Paddle2ONNX#204]
通过“手把手教你使用ONNXRunTime部署PP-OCR”教程将模型转为ONNX后，按照模型对应的.yml 中  ` Eval[RecResizeImg][image_shape: [3, 32, 320]]` 在jetosnagx xavier ONNX转trt时会报 `ttributeError:'NoneType' object has no attribute 'serialize'`的错误，请问是打包ONNX时的占位数据的形状是什么

**Comment by PhilCuriosity** [comment]
已通过`python -m onnxsim ./ch_rec_model.onnx ./ch_rec_model_sim.onnx

Simplifying...
Traceback (most recent call last):
  File "D:\SoftwareWork\Anaconda3\lib\runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "D:\SoftwareWork\Anaconda3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "D:\SoftwareWork\Anaconda3\lib\site-packages\onnxsim\__main__.py", line 90, in <module>
    main()
  File "D:\SoftwareWork\Anaconda3\lib\site-packages\onnxsim\__main__.py", line 68, in main
    model_opt, check_ok = onnxsim.simplify(
  File "D:\SoftwareWork\Anaconda3\lib\site-packages\onnxsim\onnx_simplifier.py", line 480, in simplify
    model = fixed_point(model, infer_shapes_and_optimize, constant_folding)
  File "D:\SoftwareWork\Anaconda3\lib\site-packages\onnxsim\onnx_simplifier.py", line 381, in fixed_point
    x = func_b(x)
  File "D:\SoftwareWork\Anaconda3\lib\site-packages\onnxsim\onnx_simplifier.py", line 470, in constant_folding
    res = forward_for_node_outputs(model,
  File "D:\SoftwareWork\Anaconda3\lib\site-packages\onnxsim\onnx_simplifier.py", line 226, in forward_for_node_outputs
    res = forward(model,
  File "D:\SoftwareWork\Anaconda3\lib\site-packages\onnxsim\onnx_simplifier.py", line 207, in forward
    inputs.update(generate_specific_rand_input(model, {name: shape}))
  File "D:\SoftwareWork\Anaconda3\lib\site-packages\onnxsim\onnx_simplifier.py", line 98, in generate_specific_rand_input
    raise RuntimeError(
RuntimeError: The shape of input "x" has dynamic size "[-1, 3, 32, 100]", please determine the input size manually by "--dynamic-input-shape --input-shape xxx" or "--input-shape xxx". Run "python3 -m onnxsim -h" for details`
**获取到输入形状为[1,3,32,100]**

**Comment by Channingss** [comment]
@PhilCuriosity 就是提示里面的RuntimeError: The shape of input "x" has dynamic size "[-1, 3, 32, 100]"

**Comment by PhilCuriosity** [comment]
> @PhilCuriosity 就是提示里面的RuntimeError: The shape of input "x" has dynamic size "[-1, 3, 32, 100]"

好的，谢谢
