### ISSUE TITLE
ONNX2TRT： ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1

### ISSUE THREAD

**Issue by PhilCuriosity** [PaddlePaddle/Paddle2ONNX#208]
使用icdar数据集（筛选出英文和数字进行训练的）训练出来的PPOCR，将export_model.py输入设置为[1,3,32,320]
![微信截图_20210310104646](https://user-images.githubusercontent.com/52873355/110568487-0a1ddb00-818e-11eb-8784-9a6c4e416185.png)
使用`python export_model.py -c D:\PyProject\PaddleOCR-dygraph\configs\rec\multi_language/rec_en_number_lite_train.yml -o Global.pretrained_model=D:\PyProject\PaddleOCR-dygraph\tools\output\rec_en_number_lite/best_accuracy Global.load_static_weights=False Global.save_inference_dir=D:\PyProject\PaddleOCR-dygraph\tools\myicdr_320
`转换为inference模型
使用`paddle2onnx --model_dir myicdar_320 --model_filename inference.pdmodel  --params_filename  inference.pdiparams   --save_file ppocr_rec.onnx  --opset_version 11 --enable_onnx_checker True`转换为onnx模型。在Jetson AGX 上ONNX2TRT报错如下：
[TensorRT] INFO: ModelImporter.cpp:135: No importer registered for op: ScatterND. Attempting to import as plugin.
[TensorRT] INFO: builtin_op_importers.cpp:3659: Searching for plugin: ScatterND, plugin_version: 1, plugin_namespace: 
[TensorRT] **ERROR: INVALID_ARGUMENT: getPluginCreator could not find plugin ScatterND version 1**
In node -1 (importFallbackPluginImporter): UNSUPPORTED_NODE: Assertion failed: creator && "Plugin not found, are the plugin name, version, and namespace correct?"
Completed parsing of ONNX file
Building an engine from file ./ppocr_rec_sim.onnx; this may take a while...
num layers: 252
=================> batch_size 1
[TensorRT] ERROR: Network must have at least one output
[TensorRT] ERROR: Network validation failed.
engine: None
Completed creating Engine
Traceback (most recent call last):
  File "export.py", line 54, in <module>
    ONNX_build_engine()
  File "export.py", line 38, in ONNX_build_engine
    f.write(engine.serialize())
AttributeError: 'NoneType' object has no attribute 'serialize'
 使用【手把手教你使用ONNXRunTime部署PP-OCR】教程中直接导出的ONNX去转换为TRT却不会出现这个错误。我想问一下【ScatterND version 1】这个插件是你们后来自己嵌入的嘛，还有ONNX2TRT有没有办法解决这个问题？

**Comment by PhilCuriosity** [comment]
tensorrt那边回答说：tensorrt尚不支持ScatterND

**Comment by PhilCuriosity** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/issues/212
