### ISSUE TITLE
paddle2onnx对NLP的常用算子的支持

### ISSUE THREAD

**Issue by wdhxek** [PaddlePaddle/Paddle2ONNX#213]
您好，

目前在项目支持列表中，看到所支持的模型多是CV的。对NLP中常用的lstm/gru/crf等序列模型的支持很少。用paddle2onnx用静态图的方式转换nlp中的[lac项目](https://github.com/baidu/lac), bigru-crf架构，发现不支持gru和crf-decoding两个算子
细节：
paddle2的版本:2.0.1
lac版本：2.1.0
paddle2onnx的版本：0.5
onnx的版本:1.8.1

错误日志如下
Traceback (most recent call last):
  File "/home/gsliu/anaconda3/envs/paddle2/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/convert.py", line 74, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/convert.py", line 31, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 208, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 162, in build_op_nodes
    OpMapper.check_support_status(node_map, self.opset_version)
  File "/home/gsliu/anaconda3/envs/paddle2/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 2 ops are not supported yet
=========== gru ===========
=========== crf_decoding ===========

-----
1 后续对NLP相关的序列架构的算子支持有无确定的时间计划呢？
2 是否有一些简明教程，支持自定制op加入到paddle2onnx中加快开发进度？

谢谢，祝好

**Comment by jiangjiajun** [comment]
你好，感谢对Paddle2ONNX的关注，Paddle2ONNX当前已经对部分NLP OP进行支持，但仍然较少，在下个Q我们会增加NLP更多OP算子的支持。

当前你这里列的两个OP，其中GRU我们会尽快开发支持，而crf_decoding这个OP目前暂无计划。

关于自定制OP这个建议非常好，我们会在下个Q推动完善文档说明

**Comment by znsoftm** [comment]
好主意，如果有自定义算子支持功能，可以方便大家扩展，这样也可以提高兼容速度。

**Comment by wdhxek** [comment]
好的，期待！
