### ISSUE TITLE
Seems we need add unit test to make sure onnx work properly.

### ISSUE THREAD

**Issue by pkuyym** [PaddlePaddle/Paddle2ONNX#22]
I execute `sh setup.sh` and all python dependencies are installed successfully. However, I can't run `convert.py` and the error message is:

```
Traceback (most recent call last):
  File "convert.py", line 18, in <module>
    from onnx import helper, checker
  File "/usr/local/lib/python2.7/dist-packages/onnx/__init__.py", line 10, in <module>
    import onnx.helper  # noqa
  File "/usr/local/lib/python2.7/dist-packages/onnx/helper.py", line 15, in <module>
    import onnx.defs as defs
  File "/usr/local/lib/python2.7/dist-packages/onnx/defs/__init__.py", line 6, in <module>
    import onnx.onnx_cpp2py_export.defs as C
ImportError: /usr/local/lib/python2.7/dist-packages/onnx/onnx_cpp2py_export.so: undefined symbol: _ZNK6google8protobuf7Message13SpaceUsedLongEv
```

**Comment by kuke** [comment]
It should be a known problem in onnx, see:

https://github.com/onnx/onnx/issues/489
https://github.com/onnx/onnx-caffe2/issues/19

**Comment by pkuyym** [comment]
@kuke Thanks, I suspect that incorrect version of `protoc` would results in the failure. So we should make the installation for onnx more robust.
