### ISSUE TITLE
please check whether the model file is complete or damaged.??

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle2ONNX#236]
paddle2onnx --model_dir C:\Users\baidu\inference_model\  --save_file C:\Users\baidu\inference_model_ok --opset_version 11 --enable_onnx_checker True

C:\Users\baidu\inference_model\    文件夹
__model__
__params__
model.yml

提示报错  我的模型下面也没这文件
UnavailableError: Load operator fail to open file C:\Users\baidu\inference_model\bn4c_branch2c_scale, please check whether the model file is complete or damaged.
      [Hint: Expected static_cast<bool>(fin) == true, but received static_cast<bool>(fin):0 != true:1.] (at D:\v2.0.1\paddle\paddle/fluid/operators/load_op.h:41)

目标检测模型 FasterRCNN

**Comment by jiangjiajun** [comment]
命令改为
`paddle2onnx --model_dir C:\Users\baidu\inference_model\ --model_filename model --params_filename params --save_file C:\Users\baidu\inference_model_ok --opset_version 11 --enable_onnx_checker True`

**Comment by monkeycc** [comment]
The behavior of expression A - B has been unified with elementwise_sub(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_sub(X, Y, axis=0) instead of A - B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
d:\anaconda3\envs\pyqt5\lib\site-packages\paddle\fluid\layers\math_op_patch.py:298: UserWarning: d:\anaconda3\envs\pyqt5\lib\site-packages\paddle2onnx\op_mapper\custom_paddle_op\generate_proposals.py:42
The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
Traceback (most recent call last):
  File "d:\anaconda3\envs\pyqt5\lib\site-packages\paddle2onnx\op_mapper\op_mapper.py", line 102, in mapping
    graph.opset_version)
  File "d:\anaconda3\envs\pyqt5\lib\site-packages\paddle2onnx\op_mapper\op_mapper.py", line 162, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError:
There's 2 ops are not supported in opset version 11, please try opset version >= 12.
=========== greater_equal ===========
=========== less_equal ===========


During handling of the above exception, another exception occurred:
....
Exception: Error happened when mapping node ['generate_proposals_0'] to onnx, which op_type is 'generate_proposals' with inputs: {'Anchors': ['anchor_generator_0.tmp_0'], 'BboxDeltas': ['rpn_bbox_pred_fpn2.tmp_1'], 'ImInfo': ['im_info'], 'Scores': ['rpn_cls_prob_fpn2.tmp_0'], 'Variances': ['anchor_generator_0.tmp_1']} and outputs: {'RpnRoiProbs': ['generate_proposals_0.tmp_1'], 'RpnRois': ['generate_proposals_0.tmp_0'], 'RpnRoisLod': ['generate_proposals_0.tmp_2']}, specific error:
There's 2 ops are not supported in opset version 11, please try opset version >= 12.
=========== greater_equal ===========
=========== less_equal ===========


-------------------------------------------------------------------------------------
按照提示  我改为 12 之后

The behavior of expression A / B has been unified with elementwise_div(X, Y, axis=-1) from Paddle 2.0. If your code works well in the older versions but crashes in this version, try to use elementwise_div(X, Y, axis=0) instead of A / B. This transitional warning will be dropped in the future.
  op_type, op_type, EXPRESSION_MAP[method_name]))
2021-04-11 10:19:22 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-04-11 10:19:23 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-04-11 10:19:23 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-04-11 10:19:23 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-04-11 10:19:23 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-04-11 10:19:23 [WARNING]   Operator:multiclass_nms only supports input[batch_size] == 1.
2021-04-11 10:19:25 [INFO]      ONNX model genarated is valid.
Traceback (most recent call last):
  File "d:\anaconda3\envs\pyqt5\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\anaconda3\envs\pyqt5\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\anaconda3\envs\pyqt5\Scripts\paddle2onnx.exe\__main__.py", line 7, in <module>
  File "d:\anaconda3\envs\pyqt5\lib\site-packages\paddle2onnx\command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "d:\anaconda3\envs\pyqt5\lib\site-packages\paddle2onnx\command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "d:\anaconda3\envs\pyqt5\lib\site-packages\paddle2onnx\convert.py", line 77, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "d:\anaconda3\envs\pyqt5\lib\site-packages\paddle2onnx\convert.py", line 40, in export_onnx
    with open(save_file, 'wb') as f:
PermissionError: [Errno 13] Permission denied: 'C:\\Users\\baidu\\inference_model_ok'

**Comment by jiangjiajun** [comment]
嗯，这是因为你没有文件写的权限，你的命令行终端在启动时，选择使用管理员权限
