### ISSUE TITLE
3个op不支持

### ISSUE THREAD

**Issue by xk0221** [PaddlePaddle/Paddle2ONNX#289]
你好，我在从paddle转onnx时有三个op不支持。报错信息是
```
Traceback (most recent call last):
  File "/localdata/kunx/rev/env/2.1.0+617/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')())
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/command.py", line 142, in main
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/command.py", line 114, in program2onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 77, in program2onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 32, in export_onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
NotImplementedError: 
There's 3 ops are not supported yet
=========== sum ===========
=========== top_k ===========
=========== gru ===========
```
但从支持的op list 来看至少sum是支持的，所以请问为什么会这样，以及我是否可以绕过这些问题。

**Comment by xk0221** [comment]
paddle.version = 2.1.1
paddle2onnx.version = 0.6

**Comment by yeliang2258** [comment]
您好，请提供一下模型，谢谢

**Comment by xk0221** [comment]
抱歉这是公司内部代码，不能传出来。

**Comment by jiangjiajun** [comment]
麻烦拉一下github最新的代码，重新安装测试下

**Comment by xk0221** [comment]
最新的是指release/0.7吗，我试了还是不行。

**Comment by yeliang2258** [comment]
develop试试

**Comment by yeliang2258** [comment]
另外sum是一直支持的一个op

**Comment by xk0221** [comment]
试了develop,依然是这样
```
Traceback (most recent call last):
  File "/localdata/kunx/rev/env/2.1.0+617/bin/paddle2onnx", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')())
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/command.py", line 142, in main
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/command.py", line 114, in program2onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 77, in program2onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 32, in export_onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
NotImplementedError: 
There's 3 ops are not supported yet
=========== sum ===========
=========== top_k ===========
=========== gru ===========```

**Comment by yeliang2258** [comment]
建议您再检查一下模型，看看使用文档

**Comment by jiangjiajun** [comment]
> 试了develop,依然是这样
> 
> ```
> Traceback (most recent call last):
>   File "/localdata/kunx/rev/env/2.1.0+617/bin/paddle2onnx", line 33, in <module>
>     sys.exit(load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')())
>   File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/command.py", line 142, in main
>   File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/command.py", line 114, in program2onnx
>   File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 77, in program2onnx
>   File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 32, in export_onnx
>   File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
>   File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
>   File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
> NotImplementedError: 
> There's 3 ops are not supported yet
> =========== sum ===========
> =========== top_k ===========
> =========== gru ===========```
> ```

这个报错信息能全部截出来吗

**Comment by xk0221** [comment]
` DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2021-08-05 08:23:15 [WARNING]   Although input_spec is specified, TranslatedLayer is not support prune. An Complete network will be exported.
Traceback (most recent call last):
  File "export2onnx.py", line 39, in <module>
    export_dete()
  File "export2onnx.py", line 37, in export_dete
    paddle.onnx.export(model, 'carplate_rec', input_spec=[x_spec], opset_version=11)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle/onnx/export.py", line 105, in export
    **configs)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 147, in dygraph2onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 32, in export_onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
NotImplementedError: 
There's 3 ops are not supported yet
=========== gru ===========
=========== sum ===========
=========== top_k ===========
`

**Comment by xk0221** [comment]
`/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2021-08-05 08:23:15 [WARNING]   Although input_spec is specified, TranslatedLayer is not support prune. An Complete network will be exported.
Traceback (most recent call last):
  File "export2onnx.py", line 39, in <module>
    export_dete()
  File "export2onnx.py", line 37, in export_dete
    paddle.onnx.export(model, 'carplate_rec', input_spec=[x_spec], opset_version=11)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle/onnx/export.py", line 105, in export
    **configs)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 147, in dygraph2onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 32, in export_onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
NotImplementedError: 
There's 3 ops are not supported yet
=========== gru ===========
=========== sum ===========
=========== top_k ===========`

**Comment by xk0221** [comment]
```
/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/distutils/__init__.py:4: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
2021-08-05 08:23:15 [WARNING]   Although input_spec is specified, TranslatedLayer is not support prune. An Complete network will be exported.
Traceback (most recent call last):
  File "export2onnx.py", line 39, in <module>
    export_dete()
  File "export2onnx.py", line 37, in export_dete
    paddle.onnx.export(model, 'carplate_rec', input_spec=[x_spec], opset_version=11)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle/onnx/export.py", line 105, in export
    **configs)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 147, in dygraph2onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/convert.py", line 32, in export_onnx
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 229, in build
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx-0.6-py3.6.egg/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
NotImplementedError: 
There's 3 ops are not supported yet
=========== gru ===========
=========== sum ===========
=========== top_k ===========
```

**Comment by jiangjiajun** [comment]
上面没有更多其它提示信息了吗，当前这里sum提示不支持，但其实这个OP是在paddle2onnx中已经支持了的。这里之所以会提示sum不提示，可能是因为在转sum时出错
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/paddle2onnx/op_mapper/math.py#L346

看下从命令行的命令执行那行开始，是否有其它日志没附上来

**Comment by xk0221** [comment]
你们的sum代码里少加了@classmethod
