### ISSUE TITLE
3个op不支持

### ISSUE THREAD

**Issue by WingEdge777** [PaddlePaddle/Paddle2ONNX#292]
```
Traceback (most recent call last):
  File "/usr/local/bin/paddle2onnx", line 10, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/convert.py", line 77, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/convert.py", line 32, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/graph/onnx_graph.py", line 229, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
    OpMapper.check_support_status(node_map, self.opset_version)
  File "/usr/local/lib/python3.6/dist-packages/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 3 ops are not supported yet
=========== sequence_pool ===========
=========== lstm ===========
=========== sequence_softmax ===========
```
paddle version : 1.8.5
paddle2onnx version : 0.7

模型是 paddle videotag下的 attention_lstm

**Comment by yeliang2258** [comment]
为了更快解决你的问题，请提供一下model

**Comment by 754467737** [comment]
pp-TSM 里边的NotImplementedError:
There's 1 ops are not supported yet
=========== temporal_shift ===========
temporal_shift也不支持，怎么办？

**Comment by CLIsVeryOK** [comment]
@handoku 有解决嘛？同问，也是paddle videotag下的 attention_lstm模型

**Comment by WingEdge777** [comment]
@CLIsVeryOK 没解决，直接上了paddle模型

**Comment by FitzShen666** [comment]
PaddlePaddle v2.2.1
paddle2onnx 0.9.0

遇到同样的问题，请问是否会对这些算子添加支持呢？

**Comment by yeliang2258** [comment]
您好，后期我们会排期支持，麻烦你安装最新版本paddle2onnx develop，然后将具体的不支持OP截图提供一下，谢谢

**Comment by FitzShen666** [comment]
> 您好，后期我们会排期支持，麻烦你安装最新版本paddle2onnx develop，然后将具体的不支持OP截图提供一下，谢谢

感谢您的回复：

刚刚将paddle2onnx更新到最新的版本：

在尝试导出videotag下的attention_lstm会出现以下报错：

There's 3 ops are not supported yet
=========== sequence_softmax ===========
=========== sequence_pool ===========
=========== lstm ===========

同样的，尝试导出MultimodalVideoTag下的模型，会出现以下报错：

There's 5 ops are not supported yet
=========== sequence_unpad ===========
=========== sequence_softmax ===========
=========== lstm ===========
=========== sequence_conv ===========
=========== sequence_pool ===========

模型版本均为PaddlePaddle v2.2.1，使用save_inference_model导出的推理模型。

**Comment by CLIsVeryOK** [comment]
您的来信已收到，谢谢！陈雷同济大学测绘与地理信息学院Thanks for your attention.Chen Lei
College of survey and geo-information of Tongji university

**Comment by CLIsVeryOK** [comment]
您的来信已收到，谢谢！陈雷同济大学测绘与地理信息学院Thanks for your attention.Chen Lei
College of survey and geo-information of Tongji university

**Comment by CLIsVeryOK** [comment]
您的来信已收到，谢谢！陈雷同济大学测绘与地理信息学院Thanks for your attention.Chen Lei
College of survey and geo-information of Tongji university
