### ISSUE TITLE
top_k_v2和im2sequence

### ISSUE THREAD

**Issue by xk0221** [PaddlePaddle/Paddle2ONNX#294]
我的模型需要的是top_k，但是paddle2onnx支持的是top_k_v2,所以我在op_mapper.py下的search中把@op_maper('top_k_v2')改成了@op_maper('top_k')，但是会报
```
Traceback (most recent call last):
  File "export2onnx.py", line 39, in <module>
    export_dete()
  File "export2onnx.py", line 37, in export_dete
    paddle.onnx.export(model, 'carplate_rec', input_spec=[x_spec], opset_version=11)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle/onnx/export.py", line 105, in export
    **configs)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx/convert.py", line 147, in dygraph2onnx
    verbose)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx/convert.py", line 32, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx/graph/onnx_graph.py", line 229, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx/graph/onnx_graph.py", line 186, in build_op_nodes
    OpMapper.mapping(self, node)
  File "/localdata/kunx/rev/env/2.1.0+617/lib/python3.6/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 115, in mapping
    node.outputs) + str(e))
Exception: Error happened when mapping node ['top_k_0'] to onnx, which op_type is 'top_k' with inputs: {'K': [], 'X': ['fc_2.tmp_3']} and outputs: {'Indices': ['top_k_0.tmp_1'], 'Out': ['top_k_0.tmp_0']}, specific error: value "None" is not valid attribute data type.
```
请问怎么解决以及top_k和top_k_v2差别在哪。
此外im2sequence的代码有错
   ```
slice_node_blocks = list()
        for i in range(out_h):
            for j in range(out_w):
                starts_node = graph.make_node(
                    'Constant',
                    dtype=dtypes.ONNX.INT64,
                    dims=[4],
                    value=[0, 0, h_steps[i][0], w_steps[j][0]])
                ends_node = graph.make_node(
                    'Constant',
                    dtype=dtypes.ONNX.INT64,
                    dims=[4],
                    value=[999999, 999999, h_steps[i][1], w_steps[j][1]])
                nodes.extend([starts_node, ends_node])

                slice_block_node = graph.make_node(
                    'Slice',
                    inputs=[node.input('X', 0), starts_node, ends_node])
                flatten_block_node = graph.make_node(
                    "Flatten", inputs=[slice_block_node], axis=0)
                nodes.extend([slice_block_node, flatten_block_node])
        concat_block_node = graph.make_node(
            "Concat",
            inputs=slice_node_blocks,
            outputs=node.output('Out'),
            axis=0)
```

concat_block_node = graph.make_node上面的两个nodes之前并没有定义，在转模型的时候这一点也会报错。

**Comment by jiangjiajun** [comment]
模型方便上传一下么（通过百度网盘或其它方式）


--------
另外当前转换模型的应用场景是什么呢？

**Comment by xk0221** [comment]
不好意思是内部部模型不能上传。
我只是想知道`im2sequence.py`中68和61行`nodes`没有定义的问题怎么修改，
以及top_k_v2和top_k的区别，谢谢
