### ISSUE TITLE
尝试转换PP-Structure中表格结构模型，9 ops不支持

### ISSUE THREAD

**Issue by SWHL** [PaddlePaddle/Paddle2ONNX#295]
#### 转换环境
-  `OS`: CentOS
- `paddle2onnx`: 0.7
- `PaddleOCR`: release/2.2

#### 转换代码
```shell
paddle2onnx --model_dir ${save_inference_path} \
            --model_filename inference.pdmodel \
            --params_filename inference.pdiparams \
            --save_file ${save_onnx_path} \
            --opset_version 12
```

#### 报错信息
```python
Traceback (most recent call last):
  File "/home/SWHL/miniconda3/envs/SWHL/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle2onnx/command.py", line 142, in main
    enable_onnx_checker=args.enable_onnx_checker)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle2onnx/command.py", line 114, in program2onnx
    enable_onnx_checker=enable_onnx_checker)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle2onnx/convert.py", line 77, in program2onnx
    export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle2onnx/convert.py", line 32, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version, verbose)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 229, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 183, in build_op_nodes
    OpMapper.check_support_status(node_map, self.opset_version)
  File "/home/SWHL/miniconda3/envs/SWHL/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 144, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 9 ops are not supported yet
=========== lod_array_length ===========
=========== one_hot_v2 ===========
=========== less_than ===========
=========== logical_not ===========
=========== select_input ===========
=========== write_to_array ===========
=========== conditional_block ===========
=========== tensor_array_to_tensor ===========
=========== while ===========
```

希望可以帮助解决一下，十分感谢！

**Comment by jiangjiajun** [comment]
请问下当前你将这个模型转为ONNX的目的和应用场景是什么呢？

**Comment by SWHL** [comment]
目的：表格结构分析
应用场景：
类似下图的表格结构重建
![image](https://user-images.githubusercontent.com/28639377/128481497-56fd4c31-ef02-43fd-ae6e-581e96a5044a.png)

**Comment by jiangjiajun** [comment]
你好，这个模型我们正在分析中，另外上面问到的应用场景主要指的是，你为什么需要将模型转成ONNX使用呢，直接使用Paddle模型有什么问题呢？

**Comment by SWHL** [comment]
> 你好，这个模型我们正在分析中，另外上面问到的应用场景主要指的是，你为什么需要将模型转成ONNX使用呢，直接使用Paddle模型有什么问题呢？

- 主要应用场景指的是将上图中汇票解析为对应的excel，便于后续的编辑处理。（由于某种原因不能直接拿到直接对应的原始数据）
- 转为ONNX使用的的原因：
    - 主要是对onnxruntime作为推理引擎使用较为熟悉
    - 同时因为目前项目中其他模型都是onnx格式，为了后续地便于整合

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
