### ISSUE TITLE
paddleClas里面的商品识别模型检测模型ppyolov2_r50vd_dcn_mainbody_v1.0_infer，转onnx，三个操作不支持

### ISSUE THREAD

**Issue by xinsuinizhuan** [PaddlePaddle/Paddle2ONNX#303]
使用paddleClas转换商品识别模型检测模型时，不支持其中三个操作：
(paddle) xxxx>paddle2onnx --model_dir D:\vison_software\paddle\Paddle2ONNX-develop\models\ppyolov2_r50vd_dcn_mainbody_v1.0_infer\  --save_file onnx_models/resnet50_onnx/det_model.onnx  --opset_version 11 --enable_onnx_checker True --model_filename inference.pdmodel --params_filename inference.pdiparams
Traceback (most recent call last):
  File "C:\ProgramData\Anaconda3\envs\paddle\Scripts\paddle2onnx-script.py", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.6', 'console_scripts', 'paddle2onnx')())
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\command.py", line 142, in main
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\command.py", line 114, in program2onnx
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\convert.py", line 77, in program2onnx
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\convert.py", line 32, in export_onnx
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 229, in build
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 75, in __init__
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 185, in update_opset_version
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\op_mapper\op_mapper.py", line 119, in get_recommend_opset_version
  File "C:\ProgramData\Anaconda3\envs\paddle\lib\site-packages\paddle2onnx-0.6-py3.7.egg\paddle2onnx\op_mapper\op_mapper.py", line 160, in check_support_status
NotImplementedError:
There's 3 ops are not supported yet
=========== conditional_block ===========
=========== logical_not ===========
=========== select_input ===========

**Comment by jiangjiajun** [comment]
PPYOLOV2在导出时，是可以去掉不必要的控制流的，参考PaddleDetection的做法，建议类似的issue提到PaddleClas

**Comment by xinsuinizhuan** [comment]
如何去掉？

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
