### ISSUE TITLE
手把手教你使用ONNXRunTime部署PP-OCR 问题

### ISSUE THREAD

**Issue by RyanCCC** [PaddlePaddle/Paddle2ONNX#317]
你好，我在执行教程的时候，成功导出onnx模型，但是在加载onnx推理的时候出现以下错误，烦请解答一下，谢谢！

/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/paddle/fluid/layers/utils.py:26: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  def convert_to_list(value, n, name, dtype=np.int):
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/special/orthogonal.py:81: DeprecationWarning: `np.int` is a deprecated alias for the builtin `int`. To silence this warning, use `int` by itself. Doing this will not modify any behavior and is safe. When replacing `np.int`, you may wish to use e.g. `np.int64` or `np.int32` to specify the precision. If you wish to review your current use, check the release note link for additional information.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  from numpy import (exp, inf, pi, sqrt, floor, sin, cos, around, int,
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/sparse/sputils.py:16: DeprecationWarning: `np.typeDict` is a deprecated alias for `np.sctypeDict`.
  supported_dtypes = [np.typeDict[x] for x in supported_dtypes]
/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/scipy/linalg/__init__.py:217: DeprecationWarning: The module numpy.dual is deprecated.  Instead of using dual, use the functions directly from numpy or scipy.
  from numpy.dual import register_func

Traceback (most recent call last):
  File "onnx_inference/predict_system.py", line 190, in <module>
    main(utility.parse_args())
  File "onnx_inference/predict_system.py", line 144, in main
    text_sys = TextSystem(args)
  File "onnx_inference/predict_system.py", line 41, in __init__
    self.text_detector = predict_det.TextDetector(args)
  File "/home/aistudio/onnx_inference/predict_det.py", line 99, in __init__
    args, 'det', logger)  # paddle.jit.load(args.det_model_dir)
  File "/home/aistudio/onnx_inference/utility.py", line 107, in create_predictor
    sess = ort.InferenceSession(model_file_path)
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 158, in __init__
    self._load_model(providers or [])
  File "/opt/conda/envs/python35-paddle120-env/lib/python3.7/site-packages/onnxruntime/capi/session.py", line 177, in _load_model
    self._sess.load_model(providers)
onnxruntime.capi.onnxruntime_pybind11_state.InvalidArgument: [ONNXRuntimeError] : 2 : INVALID_ARGUMENT : Failed to load model with error: Unknown model file format version.

![image](https://user-images.githubusercontent.com/27406337/132471482-45e20c0c-20d0-4047-87cf-32823254cf83.png)

**Comment by RyanCCC** [comment]
ONNX的版本要1.7.0
