### ISSUE TITLE
2 ops are not supported

### ISSUE THREAD

**Issue by wang971124** [PaddlePaddle/Paddle2ONNX#398]
将paddleseg中的sfnetresnet50模型导出之后，将其转化为onnx时报错，提示缺少两个算子：there‘s 2 ops are not supported yet。希望官方尽快可以帮忙修复

**Comment by wang971124** [comment]
报错：
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/onnx/mapping.py:27: DeprecationWarning: np.object is a deprecated alias for the builtin object. To silence this warning, use object by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
int(TensorProto.STRING): np.dtype(np.object)
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:45: DeprecationWarning: np.bool is a deprecated alias for the builtin bool. To silence this warning, use bool by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.bool_ here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
np.bool: core.VarDesc.VarType.BOOL,
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:46: DeprecationWarning: np.float is a deprecated alias for the builtin float. To silence this warning, use float by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.float64 here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
core.VarDesc.VarType.FP32: np.float,
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:51: DeprecationWarning: np.bool is a deprecated alias for the builtin bool. To silence this warning, use bool by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.bool_ here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
core.VarDesc.VarType.BOOL: np.bool
2021-11-18 15:55:09 [WARNING]	You are use develop version of paddlepaddle
Traceback (most recent call last):
File "/home/imagex/anaconda3/envs/wang/bin/paddle2onnx", line 8, in 
sys.exit(main())
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/command.py", line 148, in main
program2onnx(
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/command.py", line 114, in program2onnx
p2o.program2onnx(
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/convert.py", line 79, in program2onnx
export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker, operator_export_type)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/convert.py", line 33, in export_onnx
onnx_graph = ONNXGraph.build(paddle_graph, opset_version, operator_export_type, verbose)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 240, in build
onnx_graph = ONNXGraph(paddle_graph, opset_version=opset_version, operator_export_type=operator_export_type)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 79, in init
self.update_opset_version()
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 194, in update_opset_version
self.opset_version = OpMapper.get_recommend_opset_version(node_map, self.opset_version)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 127, in get_recommend_opset_version
recommend_opset_version = OpMapper.check_support_status(node_map, opset_version, True)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 168, in check_support_status
raise NotImplementedError(error_info)
NotImplementedError:
There's 2 ops are not supported yet

**Comment by wang971124** [comment]
我用的sfnet_res50模型参数时在paddleseg官网提供的链接下载的

**Comment by yeliang2258** [comment]
你好，具体的OP名称是？

**Comment by wang971124** [comment]
不知道怎么查看呀

**Comment by wang971124** [comment]
![image](https://user-images.githubusercontent.com/74095885/142595499-3fb8728f-0b74-4dbb-9f5f-21e7c8915e48.png)
是从这里下载的模型参数，然后使用
![image](https://user-images.githubusercontent.com/74095885/142595625-6cc782f6-86f3-40a4-9449-331e40bc8106.png)
导出报错

**Comment by yeliang2258** [comment]
你好，报错的log信息最后会打印出那些op不支持的

**Comment by wang971124** [comment]
> 你好，报错的log信息最后会打印出那些op不支持的

/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/onnx/mapping.py:27: DeprecationWarning: np.object is a deprecated alias for the builtin object. To silence this warning, use object by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
int(TensorProto.STRING): np.dtype(np.object)
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:45: DeprecationWarning: np.bool is a deprecated alias for the builtin bool. To silence this warning, use bool by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.bool_ here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
np.bool: core.VarDesc.VarType.BOOL,
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:46: DeprecationWarning: np.float is a deprecated alias for the builtin float. To silence this warning, use float by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.float64 here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
core.VarDesc.VarType.FP32: np.float,
/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/constant/dtypes.py:51: DeprecationWarning: np.bool is a deprecated alias for the builtin bool. To silence this warning, use bool by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use np.bool_ here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
core.VarDesc.VarType.BOOL: np.bool
2021-11-18 15:55:09 [WARNING]	You are use develop version of paddlepaddle
Traceback (most recent call last):
File "/home/imagex/anaconda3/envs/wang/bin/paddle2onnx", line 8, in
sys.exit(main())
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/command.py", line 148, in main
program2onnx(
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/command.py", line 114, in program2onnx
p2o.program2onnx(
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/convert.py", line 79, in program2onnx
export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker, operator_export_type)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/convert.py", line 33, in export_onnx
onnx_graph = ONNXGraph.build(paddle_graph, opset_version, operator_export_type, verbose)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 240, in build
onnx_graph = ONNXGraph(paddle_graph, opset_version=opset_version, operator_export_type=operator_export_type)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 79, in init
self.update_opset_version()
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 194, in update_opset_version
self.opset_version = OpMapper.get_recommend_opset_version(node_map, self.opset_version)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 127, in get_recommend_opset_version
recommend_opset_version = OpMapper.check_support_status(node_map, opset_version, True)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 168, in check_support_status
raise NotImplementedError(error_info)
NotImplementedError:
There's 2 ops are not supported yet

**Comment by jiangjiajun** [comment]
哪些OP不支持，输出在整个屏幕在最下面

**Comment by wang971124** [comment]
File "/home/imagex/anaconda3/envs/wang/bin/paddle2onnx", line 8, in
sys.exit(main())
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/command.py", line 148, in main
program2onnx(
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/command.py", line 114, in program2onnx
p2o.program2onnx(
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/convert.py", line 79, in program2onnx
export_onnx(paddle_graph, save_file, opset_version, enable_onnx_checker, operator_export_type)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/convert.py", line 33, in export_onnx
onnx_graph = ONNXGraph.build(paddle_graph, opset_version, operator_export_type, verbose)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 240, in build
onnx_graph = ONNXGraph(paddle_graph, opset_version=opset_version, operator_export_type=operator_export_type)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 79, in init
self.update_opset_version()
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 194, in update_opset_version
self.opset_version = OpMapper.get_recommend_opset_version(node_map, self.opset_version)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 127, in get_recommend_opset_version
recommend_opset_version = OpMapper.check_support_status(node_map, opset_version, True)
File "/home/imagex/anaconda3/envs/wang/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 168, in check_support_status
raise NotImplementedError(error_info)
NotImplementedError:
There's 2 ops are not supported yet

**Comment by yeliang2258** [comment]
用户您好，Paddle2ONNX遇到不支持的OP会在最后打印出对应的OP名称，您可以找一下，然后将完整的信息贴出来，加快我们的处理进度，谢谢。

**Comment by wang971124** [comment]
grid_sampler
linspace

**Comment by yeliang2258** [comment]
收到，我们会尽快排期进行这两个OP的支持

**Comment by jiangjiajun** [comment]
Hi, @wang971124 我们准备了一份简单的问题调研（半分钟可完成），如有时间可帮忙完成调研，帮助Paddle2ONNX做得更好, 谢谢~ https://iwenjuan.baidu.com/?code=r8hu2s

**Comment by cookiewang1998** [comment]
select_input
conditional_block
这两个算子不支持

**Comment by Change0028** [comment]
您好，我遇到了类似的问题，是以下两个算子不支持：
less_than
where

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
