### ISSUE TITLE
paddle2onnx报错

### ISSUE THREAD

**Issue by CV-deeplearning** [PaddlePaddle/Paddle2ONNX#415]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**基于paddle ocr训练的表格识别模型，转成onnx时报错！！！**
用paddle训练的表格识别模型，转onnx时报错，难道是不支持GRU操作。

**更多信息 :**
 - 用于部署的推理引擎:tensorRT
 - 为什么需要转换为ONNX格式：用tensorRT加速
 - Paddle2ONNX版本:2.1.1
 - 你的联系方式(Email/Wechat/Phone):1151583746@qq.com

****
Traceback (most recent call last):
  File "/home/work/anaconda3/envs/torch16_py37/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/command.py", line 184, in main
    input_shape_dict=input_shape_dict)
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/command.py", line 148, in program2onnx
    operator_export_type=operator_export_type)
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/convert.py", line 84, in program2onnx
    enable_onnx_checker, operator_export_type)
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/convert.py", line 34, in export_onnx
    operator_export_type, verbose)
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 240, in build
    onnx_graph = ONNXGraph(paddle_graph, opset_version=opset_version, operator_export_type=operator_export_type)
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 79, in __init__
    self.update_opset_version()
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 194, in update_opset_version
    self.opset_version = OpMapper.get_recommend_opset_version(node_map, self.opset_version)
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 129, in get_recommend_opset_version
    node_map, opset_version, True)
  File "/home/work/anaconda3/envs/torch16_py37/lib/python3.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 174, in check_support_status
    raise NotImplementedError(error_info)
NotImplementedError: 
There's 7 ops are not supported yet
=========== select_input ===========
=========== lod_array_length ===========
=========== write_to_array ===========
=========== tensor_array_to_tensor ===========
=========== one_hot_v2 ===========
=========== while ===========
=========== conditional_block ===========

**其他信息**

**Comment by yeliang2258** [comment]
你好，Paddle2ONNX目前尚不支持带有控制流模型的转换。你可以使用PaddleInference进行部署，PaddleInference集成了TensorRT，可以开启TRT进行高效的部署。https://paddleinference.paddlepaddle.org.cn/product_introduction/inference_intro.html

**Comment by yeliang2258** [comment]
另外，我们准备了一份简单的问题调研（半分钟可完成），如有时间可帮忙完成调研，帮助Paddle2ONNX做得更好 https://iwenjuan.baidu.com/?code=r8hu2s
谢谢啦！

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
