### ISSUE TITLE
Due to the operator:multiclass_nms3, the converted ONNX model will only supports 

### ISSUE THREAD

**Issue by monkeycc** [PaddlePaddle/Paddle2ONNX#419]
**问题描述**

yolov3_ darknet53_ 270e_ VOC 训练出来的模型

image_shape:[3,608,608]

Paddle2onnx conversion yolov3_ darknet53_ 270e_ VOC model
[WARNING]   Due to the operator:multiclass_nms3, the converted ONNX model will only supports input[batch_size] == 1.

 paddle2onnx 
--model_dir D:\PaddleDetection\output\yolov3_darknet53_270e_voc_OK\yolov3_darknet53_270e_voc 
--model_filename model.pdmodel --params_filename model.pdiparams --opset_version 11 
--save_file D:\PaddleDetection\output\yolov3_darknet53_270e_voc_OK\onnx\yolov3.onnx

D:\anaconda3\envs\PaddleDetection\lib\site-packages\onnx\helper.py:343: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  is_iterable = isinstance(value, collections.Iterable)

2021-12-09 16:44:59 [WARNING]   Due to the operator:multiclass_nms3, the converted ONNX model will only supports input[batch_size] == 1.
2021-12-09 16:45:01 [INFO]      ONNX model generated is valid.
2021-12-09 16:45:03 [INFO]      ONNX model saved in D:\PaddleDetection\output\yolov3_darknet53_270e_voc_OK\onnx\yolov3.onnx

[WARNING]   Due to the operator:multiclass_nms3, the converted ONNX model will only supports input[batch_size] == 1.

---------------------

转换为  openvino
报错

python mo_onnx.py 
--input_model F:\yolov3_darknet53_270e_voc_OK\onnx\yolov3.onnx 
--output_dir F:\yolov3_darknet53_270e_voc_OK\onnx\yolov3 --input_shape [1,3,608,608]

Model Optimizer arguments:
Common parameters:
        - Path to the Input Model:      F:\yolov3_darknet53_270e_voc_OK\onnx\yolov3.onnx
        - Path for generated IR:        F:\yolov3_darknet53_270e_voc_OK\onnx\yolov3
        - IR output name:       yolov3
        - Log level:    ERROR
        - Batch:        Not specified, inherited from the model
        - Input layers:         Not specified, inherited from the model
        - Output layers:        Not specified, inherited from the model
        - Input shapes:         [1,3,608,608]
        - Mean values:  Not specified
        - Scale values:         Not specified
        - Scale factor:         Not specified
        - Precision of IR:      FP32
        - Enable fusing:        True
        - Enable grouped convolutions fusing:   True
        - Move mean values to preprocess section:       None
        - Reverse input channels:       False
ONNX specific parameters:
        - Inference Engine found in:    E:\Intel\openvino_2021.4.689\python\python3.8\openvino
Inference Engine version:       2021.4.1-3926-14e67d86634-releases/2021/4
Model Optimizer version:        2021.4.1-3926-14e67d86634-releases/2021/4

[ ERROR ]  Exception occurred during running replacer "REPLACEMENT_ID" (<class 
'extensions.front.user_data_repack.UserDataRepack'>): Original placeholders: 'im_shape, image, scale_factor'. Freezing was requested for ''. --input_shape was provided without --input. Can not deduce which node shape to override

**Comment by jiangjiajun** [comment]
你好，openvino部署yolov3参考此文档转换即可 https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/experimental/openvino_ppdet_cn.md

另外也麻烦抽出半分钟时间帮我们完成一个小调研，谢谢你 https://wenjuan.baidu-int.com/?code=r8hu2s

**Comment by monkeycc** [comment]
@jiangjiajun 

` python onnn.py`


```


===============================


You are using a nms convertor for OpenVINO!


===============================


Traceback (most recent call last):
  File "onnn.py", line 7, in <module>
    model = paddle.jit.load(model_prefix)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\jit.py", line 1126, in load
    return TranslatedLayer._construct(model_path, config)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\io.py", line 1243, in _construct
    programs = _construct_program_holders(model_path, model_filename)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\io.py", line 699, in _construct_program_holders
    _load_program_desc(model_file_path))
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\io.py", line 50, in _load_program_desc
    program_desc = core.ProgramDesc(program_desc_str)
ValueError: (InvalidArgument) Failed to parse program_desc from binary string.
  [Hint: Expected desc_.ParseFromString(binary_str) == true, but received desc_.ParseFromString(binary_str):0 != true:1.] (at ..\paddle\fluid\framework\program_desc.cc:103)
```


为什么我转换 报错
```

input_shape_dict = {
    "image": [1, 3, 608, 608],
    "scale_factor": [1, 2],
    "im_shape": [1, 2]
    }
```

---------------------


有没PaddleX 2.0 的yolov3 转换openvino教程
或者一键脚本

嗯… 无法访问此页面似乎 wenjuan.baidu-int.com 关闭了连接

**Comment by jiangjiajun** [comment]
注意下面这行代码
```
model = paddle.jit.load(model_prefix)
```
例如你的模型文件是在`/User/XXX/ppdetmodels`目录下，且模型文件是`model.pdmodel`和`model.pdiparams`，那这个`model_prefix`应该是`/User/XXX/ppdetmodels/model`

再重新试下，我这里可以打开 https://wenjuan.baidu-int.com/?code=r8hu2s

**Comment by monkeycc** [comment]
@jiangjiajun 

NVIDIA-SMI 460.89       
Driver Version: 460.89       
CUDA Version: 11.2

我的环境是 python3.7   cuda11.2

nvcc -V
nvcc: NVIDIA (R) Cuda compiler driver
Copyright (c) 2005-2020 NVIDIA Corporation
Built on Mon_Nov_30_19:15:10_Pacific_Standard_Time_2020
Cuda compilation tools, release 11.2, V11.2.67
Build cuda_11.2.r11.2/compiler.29373293_0

但是提示以下错误

```
===============================


You are using a nms convertor for OpenVINO!


===============================


E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\backward.py:1697: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3,and in 3.9 it will stop working
  return list(x) if isinstance(x, collections.Sequence) else [x]
W1209 19:25:44.421654  5068 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.2, Runtime API Version: 10.2
W1209 19:25:44.428656  5068 dynamic_loader.cc:258] Note: [Recommend] copy cudnn into CUDA installation directory.
 For instance, download cudnn-10.0-windows10-x64-v7.6.5.32.zip from NVIDIA's official website,
then, unzip it and copy it into C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v10.0
You should do this according to your CUDA installation directory and CUDNN version.
Traceback (most recent call last):
  File "onnn.py", line 7, in <module>
    model = paddle.jit.load(model_prefix)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\jit.py", line 1126, in load
    return TranslatedLayer._construct(model_path, config)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\wrapped_decorator.py", line 25, in __impl__
    return wrapped_func(*args, **kwargs)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\framework.py", line 229, in __impl__
    return func(*args, **kwargs)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\io.py", line 1247, in _construct
    params_filename)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\io.py", line 714, in _construct_params_and_buffers
    programs['forward'], params_filename)
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\io.py", line 647, in _load_persistable_vars
    attrs={'file_path': var_file_path})
  File "E:\anaconda3\envs\PaddleDetection\lib\site-packages\paddle\fluid\dygraph\tracer.py", line 45, in trace_op
    not stop_gradient)
RuntimeError: (PreconditionNotMet) The third-party dynamic library (cudnn64_7.dll) that Paddle depends on is not configured correctly. (error code is 126)
  Suggestions:
  1. Check if the third-party dynamic library (e.g. CUDA, CUDNN) is installed correctly and its version is matched with paddlepaddle you installed.
  2. Configure third-party dynamic library environment variables as follows:
  - Linux: set LD_LIBRARY_PATH by `export LD_LIBRARY_PATH=...`
  - Windows: set PATH by `set PATH=XXX; (at ..\paddle\fluid\platform\dynload\dynamic_loader.cc:285)
  [operator < load_combine > error]
```


---------------
换了一个新环境 python3.8

```
E:\anaconda3\lib\site-packages\win32\lib\pywintypes.py:2: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp, sys, os
```
===============================


You are using a nms convertor for OpenVINO!


===============================
```


E:\anaconda3\lib\site-packages\paddle\fluid\backward.py:1666: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.10 it will stop working
  return list(x) if isinstance(x, collections.Sequence) else [x]
Traceback (most recent call last):
  File "E:\anaconda3\lib\site-packages\paddle2onnx-0.9.0-py3.8.egg\paddle2onnx\op_mapper\op_mapper.py", line 119, in mapping
  File "E:\anaconda3\lib\site-packages\paddle2onnx-0.9.0-py3.8.egg\paddle2onnx\op_mapper\tensor.py", line 1024, in opset_10
Exception: Resize in onnx(opset<=10) only support coordinate_transformation_mode: 'asymmetric', Try converting with opset_version 11

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "onnn.py", line 13, in <module>
    onnx_model = paddle2onnx.run_convert(model, input_shape_dict=input_shape_dict, opset_version=10)
  File "E:\anaconda3\lib\site-packages\paddle2onnx-0.9.0-py3.8.egg\paddle2onnx\__init__.py", line 72, in run_convert
  File "E:\anaconda3\lib\site-packages\paddle2onnx-0.9.0-py3.8.egg\paddle2onnx\convert.py", line 165, in dygraph2onnx
  File "E:\anaconda3\lib\site-packages\paddle2onnx-0.9.0-py3.8.egg\paddle2onnx\convert.py", line 33, in export_onnx
  File "E:\anaconda3\lib\site-packages\paddle2onnx-0.9.0-py3.8.egg\paddle2onnx\graph\onnx_graph.py", line 244, in build
  File "E:\anaconda3\lib\site-packages\paddle2onnx-0.9.0-py3.8.egg\paddle2onnx\graph\onnx_graph.py", line 199, in build_op_nodes
  File "E:\anaconda3\lib\site-packages\paddle2onnx-0.9.0-py3.8.egg\paddle2onnx\op_mapper\op_mapper.py", line 121, in mapping
Exception: Error happened when mapping node ['nearest_interp_v2_0'] to onnx, which op_type is 'nearest_interp_v2' with inputs: {'OutSize': [], 'Scale': [], 'SizeTensor': [], 'X': ['leaky_relu_58.tmp_0']} and outputs: {'Out': ['nearest_interp_v2_0.tmp_0']}, specific error: Resize in onnx(opset<=10) only support coordinate_transformation_mode: 'asymmetric', Try converting with opset_version 11

```

---------------------

<img width="309" alt="2345" src="https://user-images.githubusercontent.com/6490927/145388993-dab58078-ab2a-4b7a-a068-6e72d96b056f.png">

换了一台电脑 也是这样的  不能访问到这个网站

**Comment by jiangjiajun** [comment]
上面提示看到说到opset_version的问题，请按照这个文档来进行转换，在run_convert函数，指定opset_version为11
![image](https://user-images.githubusercontent.com/19339784/145390525-e60b0053-7bb5-45fc-9943-27f46ef5c4e0.png)

**Comment by monkeycc** [comment]
@jiangjiajun 

大佬 已经解决  可以了

-----------------

现在 PaddleX 2.0 的yolov3 
能这样转换onnx 再转换 openvino吗

**Comment by jiangjiajun** [comment]
可以

https://iwenjuan.baidu.com/?code=r8hu2s
此问卷如若电脑上打不开，可尝试使用手机网络打开
