### ISSUE TITLE
Fluid2ONNX conversion on the example

### ISSUE THREAD

**Issue by hshen14** [PaddlePaddle/Paddle2ONNX#57]
Hello, I met an issue on conversion from fluid to ONNX model on the example. Anyone can help?

-----------  Configuration Arguments -----------
fluid_model: extras/fit_a_line.inference.model/
onnx_model: test.onnx
to_print_model: False
------------------------------------------------
Traceback (most recent call last):
  File "fluid_to_onnx.py", line 143, in <module>
    convert(args)
  File "fluid_to_onnx.py", line 67, in convert
    var=var, scope=inference_scope)
  File "/home/test/paddle-onnx/fluid_onnx/variables.py", line 39, in paddle_onnx_weight
    data = _fetch_var(var.name, scope)
  File "/home/test/.local/lib/python2.7/site-packages/paddle/fluid/executor.py", line 191, in _fetch_var
    assert isinstance(name, str)
AssertionError

ONNX version: 1.2.2+ (pip install on centos 7.2)
Paddle: github Aug 28th

**Comment by kuke** [comment]
Please try the paddle 0.14 by `pip install paddlepaddle-gpu==0.14.0`
