### ISSUE TITLE
paddle2onnx 转 fairmot_dla34 模型时报错：ValueError: Support Offset[2] equal Offset[3], actually got Offset[2]==19, not equal Offset[3]==34

### ISSUE THREAD

**Issue by mzxhzhp** [PaddlePaddle/Paddle2ONNX#603]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

**使用 paddle2onnx 转 fairmot_dla34_30e_1088x608_headtracking21 模型时报错。**
**版本信息如下：**
paddle2onnx         0.9.1        
onnx                      1.9.0          
onnxruntime         1.10.0   
paddlepaddle-gpu    2.2.2    
paddledet             2.3.0          
paddlehub            2.2.0          
paddlelite             2.10 

**报错信息如下：**
paddle2onnx --model_dir fairmot_dla34_30e_1088x608_headtracking21  --model_filename model.pdmodel --params_filename model.pdiparams --save_file fairmot_dla34_30e_1088x608_headtracking21.onnx --opset_version 11 --enable_onnx_checker True

grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
/usr/local/lib/python3.7/dist-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe. 
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/usr/local/lib/python3.7/dist-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/usr/local/lib/python3.7/dist-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/usr/local/lib/python3.7/dist-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
Traceback (most recent call last):
  File "/usr/local/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/command.py", line 195, in main
    input_shape_dict=input_shape_dict)
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/command.py", line 159, in program2onnx
    operator_export_type=operator_export_type)
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/convert.py", line 88, in program2onnx
    auto_update_opset)
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/convert.py", line 36, in export_onnx
    auto_update_opset)
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/graph/onnx_graph.py", line 258, in build
    auto_update_opset=auto_update_opset)
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/graph/onnx_graph.py", line 85, in __init__
    self.update_opset_version()
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/graph/onnx_graph.py", line 203, in update_opset_version
    node_map, self.opset_version)
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/op_mapper/op_mapper.py", line 133, in get_recommend_opset_version
    node.type](node)
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/op_mapper/custom_paddle_op/deformable_conv.py", line 40, in __init__
    self.check_attribute(node)
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/op_mapper/custom_paddle_op/deformable_conv.py", line 34, in check_attribute
    node.input_shape('Offset', 0), (2, 3), 'Offset', 'equal')
  File "/usr/local/lib/python3.7/dist-packages/paddle2onnx/utils.py", line 126, in compare_attr_between_dims
    raise ValueError(expect_info + actual_info)
ValueError: Support Offset[2] equal Offset[3], actually got Offset[2]==19, not equal Offset[3]==34.

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**

**其他信息**

**Comment by yeliang2258** [comment]
你好，麻烦提供一下Paddle的inference模型，我这边验证一下，看看是什么问题，谢谢

**Comment by mzxhzhp** [comment]
> 你好，麻烦提供一下Paddle的inference模型，我这边验证一下，看看是什么问题，谢谢

inference 模型，我是在 PaddleDetection 套件源码中用下面的命令导出的：
python tools/export_model.py -c configs/mot/headtracking21/fairmot_dla34_30e_1088x608_headtracking21.yml -o weights=output/fairmot_dla34_30e_1088x608_headtracking21/fairmot_dla34_30e_1088x608_headtracking21.pdparams

fairmot_dla34_30e_1088x608_headtracking21.pdparams 模型的下载地址：
https://github.com/PaddlePaddle/PaddleDetection/blob/release/2.3/configs/mot/headtracking21/README_cn.md

**Comment by yeliang2258** [comment]
好的，你直接将你要转的模型上传到百度网盘，然后分享链接给我吧，快速定位解决问题。

**Comment by mzxhzhp** [comment]
> fairmot_dla34_30e_1088x608_headtracking21

inference格式的模型文件：fairmot_dla34_30e_1088x608_headtracking21.tar
链接：https://pan.baidu.com/s/1OvGm9Xs7DjfRnohfAMqlDg 
提取码：vrqe

**Comment by yeliang2258** [comment]
你好，你目前Paddle2ONNX只支持输入进来的offset为正方形，也就是offset_shape[2] == offset_shape[3]

**Comment by yeliang2258** [comment]
另外我们也准备了一份问卷，方便的话请抽出半分钟时间帮完成问卷 https://iwenjuan.baidu.com/?code=r8hu2s 帮助Paddle2ONNX做得更好
