### ISSUE TITLE
模型转onnx报错

### ISSUE THREAD

**Issue by wickai** [PaddlePaddle/Paddle2ONNX#620]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**
在转换模型的时候报错
环境：
onnx==1.7.0
paddle2onnx==0.9.1
#####

**问题描述**
请在此处详细的描述报错信息
命令：
paddle2onnx --model_dir ./output_dev18_pexp01/output/ --save_file ./convert_model_pexp01.onnx --
opset_version 11
报错：
grep: warning: GREP_OPTIONS is deprecated; please use an alias or script
Traceback (most recent call last):
  File "/usr/local/python2.7.15/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/command.py", line 195, in main
    input_shape_dict=input_shape_dict)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/command.py", line 159, in program2onnx
    operator_export_type=operator_export_type)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/convert.py", line 88, in program2onnx
    auto_update_opset)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/convert.py", line 36, in export_onnx
    auto_update_opset)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 262, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/graph/onnx_graph.py", line 209, in build_op_nodes
    OpMapper.mapping(self, node, self.operator_export_type)
  File "/usr/local/python2.7.15/lib/python2.7/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 124, in mapping
    node.outputs) + str(e))
Exception: Error happened when mapping node ['pool2d_0'] to onnx, which op_type is 'pool2d' with inputs: {u'X': [u'batch_norm_0.tmp_3']} and outputs: {u'Out': [u'pool2d_0.tmp_0']}, specific error: 'module' object has no attribute 'float32'

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone): 

**报错截图**

**其他信息**

**Comment by wickai** [comment]
换用paddle2onnx==0.9.0就好了。。。

**Comment by yeliang2258** [comment]
您好，请您提供一下你的模型，我这边分析一下新版本是什么原因导致转换失败，谢谢！

**Comment by shixinlishixinli** [comment]
我使用paddle2onnx-0.9.2 转换模型ch_ppocr_mobile_v2.0_rec_infer 报相同错误'module' object has no attribute 'float32'

**Comment by jiangjiajun** [comment]
@shixinlishixinli  你需要将paddle升级到最新版本

**Comment by shixinlishixinli** [comment]
> 

事实上paddle2onnx 0.9.8 也不好用,0.9.8 是用pip安装的最新版本。paddle2onnx 0.9.0 是好用的。 我的系统版本是ubuntu18.04, ubuntu20.04 好像没有这个问题

**Comment by jiangjiajun** [comment]
@shixinlishixinli 当前0.9.8上有遇到什么问题呢？
