### ISSUE TITLE
0.9.5版本，量化算子仍不支持fake_channel_wise_dequantize_max_abs, fake_quantize_range_abs_max

### ISSUE THREAD

**Issue by szNightFury** [PaddlePaddle/Paddle2ONNX#712]
![image](https://user-images.githubusercontent.com/100794088/164619791-05ab522a-5e71-47c7-9a16-005febbf4318.png)
如图，issue339我也看了，但我是新手，不太懂怎么用github，把339的代码弄下来安装是0.9.2版本，也是上面的报错。模型是普通的CNN模型，用了静态量化为int8想转为onnx用于部署在fpga上。
[model.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/8537645/model.zip)

**Comment by szNightFury** [comment]
不好意思，之前可能是我操作失误，在使用issue339后，似乎支持量化算子了，但最后还是会报错，生成失败。报错如下所示：
D:\Python\Python37\lib\site-packages\onnx\helper.py:343: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated, and in 3.8 it will stop working
  is_iterable = isinstance(value, collections.Iterable)
W0422 20:10:44.886624 18480 device_context.cc:447] Please NOTE: device: 0, GPU Compute Capability: 7.5, Driver API Version: 11.1, Runtime API Version: 10.2
W0422 20:10:44.902240 18480 device_context.cc:465] device: 0, cuDNN Version: 7.6.
2022-04-22 20:10:46 [INFO]      ONNX model generated is valid.
Traceback (most recent call last):
  File "D:\Python\Python37\lib\site-packages\paddle2onnx-0.9.2-py3.7.egg\paddle2onnx\utils.py", line 43, in check_model
  File "D:\Python\Python37\lib\site-packages\onnx\checker.py", line 104, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Nodes in a graph must be topologically sorted, however input 'dropout_2.tmp_0.quantized' of node:
name: Flatten_0 OpType: Flatten
 is not output of any previous nodes.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\Python\Python37\Scripts\paddle2onnx-script.py", line 33, in <module>
    sys.exit(load_entry_point('paddle2onnx==0.9.2', 'console_scripts', 'paddle2onnx')())
  File "D:\Python\Python37\lib\site-packages\paddle2onnx-0.9.2-py3.7.egg\paddle2onnx\command.py", line 236, in main
  File "D:\Python\Python37\lib\site-packages\paddle2onnx-0.9.2-py3.7.egg\paddle2onnx\command.py", line 190, in program2onnx
  File "D:\Python\Python37\lib\site-packages\paddle2onnx-0.9.2-py3.7.egg\paddle2onnx\convert.py", line 112, in program2onnx
  File "D:\Python\Python37\lib\site-packages\paddle2onnx-0.9.2-py3.7.egg\paddle2onnx\convert.py", line 40, in export_onnx
  File "D:\Python\Python37\lib\site-packages\paddle2onnx-0.9.2-py3.7.egg\paddle2onnx\graph\onnx_graph.py", line 446, in export_proto
  File "D:\Python\Python37\lib\site-packages\paddle2onnx-0.9.2-py3.7.egg\paddle2onnx\utils.py", line 45, in check_model
Exception: ONNX model is not valid.

**Comment by szNightFury** [comment]
使用最新的new_quantize_dev版本，onnx sim以及onnx runtime都报错，如下所示：
2022-04-22 22:42:09.3977239 [E:onnxruntime:, sequential_executor.cc:346 onnxruntime::SequentialExecutor::Execute] Non-zero status code returned while running QuantizeLinear node. Name:'QuantizeLinear_27' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\quantize_linear.cc:35 onnxruntime::PrepareForQDQ scale.Shape().NumDimensions() == 1 && scale.Shape()[0] == broadcast_dim was false. scale must be 1D tensor with size 3

Traceback (most recent call last):
  File "D:\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "D:\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "D:\Python\Python37\lib\site-packages\onnx_simplifier-0.3.6-py3.7.egg\onnxsim\__main__.py", line 90, in <module>
  File "D:\Python\Python37\lib\site-packages\onnx_simplifier-0.3.6-py3.7.egg\onnxsim\__main__.py", line 78, in main
  File "D:\Python\Python37\lib\site-packages\onnx_simplifier-0.3.6-py3.7.egg\onnxsim\onnx_simplifier.py", line 492, in simplify
  File "D:\Python\Python37\lib\site-packages\onnx_simplifier-0.3.6-py3.7.egg\onnxsim\onnx_simplifier.py", line 393, in fixed_point
  File "D:\Python\Python37\lib\site-packages\onnx_simplifier-0.3.6-py3.7.egg\onnxsim\onnx_simplifier.py", line 486, in constant_folding
  File "D:\Python\Python37\lib\site-packages\onnx_simplifier-0.3.6-py3.7.egg\onnxsim\onnx_simplifier.py", line 232, in forward_for_node_outputs
  File "D:\Python\Python37\lib\site-packages\onnx_simplifier-0.3.6-py3.7.egg\onnxsim\onnx_simplifier.py", line 216, in forward
  File "D:\Python\Python37\lib\site-packages\onnxruntime\capi\onnxruntime_inference_collection.py", line 192, in run
    return self._sess.run(output_names, input_feed, run_options)
onnxruntime.capi.onnxruntime_pybind11_state.RuntimeException: [ONNXRuntimeError] : 6 : RUNTIME_EXCEPTION : Non-zero status code returned while running QuantizeLinear node. Name:'QuantizeLinear_27' Status Message: D:\a\_work\1\s\onnxruntime\core\providers\cpu\tensor\quantize_linear.cc:35 onnxruntime::PrepareForQDQ scale.Shape().NumDimensions() == 1 && scale.Shape()[0] == broadcast_dim was false. scale must be 1D tensor with size 3
看起来像是Scale的维度问题，该怎么解决呢？

**Comment by szNightFury** [comment]
这是模型文件
[test_quant.zip](https://github.com/PaddlePaddle/Paddle2ONNX/files/8541997/test_quant.zip)

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/651
用户你好，请拉这个PR进行转换

**Comment by szNightFury** [comment]
> #651 用户你好，请拉这个PR进行转换
你好，我不太熟悉github，#651就是您那个new_quantize_dev分支吧？我装了之后是0.9.3版本，报错信息如我昨天发的最后一条信息所示

**Comment by yeliang2258** [comment]
好的，我会对你的模型进行测试，然后再反馈给你

**Comment by yeliang2258** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/pull/651
命令：
paddle2onnx --model_dir ./ --model_filename model.pdmodel --params_filename model.pdiparams --save_file model.onnx --opset_version 13 --enable_onnx_checker True --deploy_backend others

**Comment by szNightFury** [comment]
> #651 命令： paddle2onnx --model_dir ./ --model_filename model.pdmodel --params_filename model.pdiparams --save_file model.onnx --opset_version 13 --enable_onnx_checker True --deploy_backend others

你好，这个我之前试过了，可以运行，check也过了，但没法使用onnxruntime加载或者onnxsim

**Comment by yeliang2258** [comment]
我更新了代码，可以使用onnxruntime进行加载预测

**Comment by szNightFury** [comment]
> 我更新了代码，可以使用onnxruntime进行加载预测

你好，我用了新版本，确实正常通过了，但是只有在设为others的时候可以，设为onnxruntime或者tensorrt再onnxsim都会报错。还有个问题就是，生成出来的模型和simplified出来的模型用netron看貌似都还是浮点数？也没有体现出量化操作的scale那些，产生的模型看起来和没量化的是一样的

**Comment by yeliang2258** [comment]
你好，麻烦重新拉一下PR测试，修复了一个问题。现在deploy_backend可以设置为3种，onnxruntime，tensorrt和others，这个取决于你的推理引擎是不是支持加载带有Q和DQ的量化模型，如果不支持，则设置为others，我们除了生成一个float的模型，还会生成一个量化表，量化表里面存储了所有的量化信息

**Comment by szNightFury** [comment]
> 你好，麻烦重新拉一下PR测试，修复了一个问题。现在deploy_backend可以设置为3种，onnxruntime，tensorrt和others，这个取决于你的推理引擎是不是支持加载带有Q和DQ的量化模型，如果不支持，则设置为others，我们除了生成一个float的模型，还会生成一个量化表，量化表里面存储了所有的量化信息

非常感谢，it works！

**Comment by chengven027-intellif** [comment]
hi，现在还可以用这个PR嘛？ 我还是报一样的错
```
Paddle2ONNX] Start to parse PaddlePaddle model...
[Paddle2ONNX] Model file path: model/quant_infer_model.pdmodel
[Paddle2ONNX] Paramters file path: model/quant_infer_model.pdiparams
[Paddle2ONNX] Start to parsing Paddle model...
[Paddle2ONNX] [Info] The Paddle model is a quantized model. 
[Paddle2ONNX] Oops, there are some operators not supported yet, including fake_channel_wise_dequantize_max_abs,fake_quantize_moving_average_abs_max,softmax_with_cross_entropy,
[ERROR] Due to the unsupported operators, the conversion is aborted.
Aborted (core dumped)

```

**Comment by Daipuwei** [comment]
> > 我更新了代码，可以使用onnxruntime进行加载预测
> 
> 你好，我用了新版本，确实正常通过了，但是只有在设为others的时候可以，设为onnxruntime或者tensorrt再onnxsim都会报错。还有个问题就是，生成出来的模型和simplified出来的模型用netron看貌似都还是浮点数？也没有体现出量化操作的scale那些，产生的模型看起来和没量化的是一样的

您好请问能否加微信交流下，我按这个pr进行编译paddle2onnx，但是一直编译失败，请问您是怎么编译的

**Comment by PengYuan0** [comment]
> 你好，麻烦重新拉一下PR测试，修复了一个问题。现在deploy_backend可以设置为3种，onnxruntime，tensorrt和others，这个取决于你的推理引擎是不是支持加载带有Q和DQ的量化模型，如果不支持，则设置为others，我们除了生成一个float的模型，还会生成一个量化表，量化表里面存储了所有的量化信息

你好我拉这个分支下来转换还是报错[Paddle2ONNX] [Info] The Paddle model is a quantized model. 
[Paddle2ONNX] Oops, there are some operators not supported yet, including fake_channel_wise_quantize_dequantize_abs_max,fake_quantize_dequantize_moving_average_abs_max,moving_average_abs_max_scale,
[ERROR] Due to the unsupported operators, the conversion is aborted.
已中止 (核心已转储)
