### ISSUE TITLE
PaddleSeg中的Fast-SCNN转onnx出错

### ISSUE THREAD

**Issue by geoexploring** [PaddlePaddle/Paddle2ONNX#721]
库版本：
```
win10
paddle2onnx        0.9.5
paddlepaddle-gpu   2.2.0
paddleseg          2.5.0
```
利用如下命令将`PaddleSeg`中的`Fast-SCNN`转`onnx`：
```shell
paddle2onnx --model_dir ./model_dir \
                      --model_filename ./model_dir/model.pdmodel \
                      --params_filename  ./model_dir/model.pdiparams \
                      --opset_version 11 \
                      --save_file  ./model_out_dir/\
                      --input_shape_dict "{'x': [1, 3, 512, 512]}"
```

报错：
```
Traceback (most recent call last):
  File "c:\users\admin\desktop\test\venv\lib\site-packages\paddle2onnx\op_mapper\op_mapper.py", line 119, in mapping
    mapper_func(graph, node, **kw)
  File "c:\users\admin\desktop\test\venv\lib\site-packages\paddle2onnx\op_mapper\nn.py", line 186, in opset_1
    node.input_shape('X', 0), node.output_shape('Out', 0)))
Exception: Cannot convert adaptive pool with input_size: (-1, 128, 16, 16), output_size: (-1, 128, 6, 6)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "C:\Users\admin\AppData\Local\Programs\Python\Python37\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\admin\Desktop\test\venv\Scripts\paddle2onnx.exe\__main__.py", line 7, in <module>
  File "c:\users\admin\desktop\tesr\venv\lib\site-packages\paddle2onnx\command.py", line 283, in main
    auto_update_opset=args.enable_auto_update_opset)
  File "c:\users\admin\desktop\test\venv\lib\site-packages\paddle2onnx\command.py", line 210, in program2onnx
    output_names=output_names)
  File "c:\users\admin\desktop\test\venv\lib\site-packages\paddle2onnx\convert.py", line 102, in program2onnx
    output_names=output_names)
  File "c:\users\admin\desktop\test\venv\lib\site-packages\paddle2onnx\convert.py", line 37, in export_onnx
    auto_update_opset)
  File "c:\users\admin\desktop\test\venv\lib\site-packages\paddle2onnx\graph\onnx_graph.py", line 331, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "c:\users\admin\desktop\test\venv\lib\site-packages\paddle2onnx\graph\onnx_graph.py", line 209, in build_op_nodes
    OpMapper.mapping(self, node, self.operator_export_type)
  File "c:\users\admin\desktop\test\venv\lib\site-packages\paddle2onnx\op_mapper\op_mapper.py", line 124, in mapping
    node.outputs) + str(e))
Exception: Error happened when mapping node ['pool2d_3'] to onnx, which op_type is 'pool2d' with inputs: {'X': ['tmp_5']} and outputs: {'Out': ['pool2d_3.tmp_0']}, specific error: Cannot convert adaptive pool with input_size: (-1, 128, 16, 16), output_size: (-1, 128, 6, 6)
```

请问这是什么原因呢？
谢谢！

**Comment by jiangjiajun** [comment]
FastSCNN模型中存在`AdaptivePool`这个操作，而这个操作在ONNX并未支持。  AdaptivePool在某些输入情况下可以转成普通的Pool，要求是输入是输出的整数倍。 当前显示你这里AdaptivePool的输入是16, 16，而输出是6，6， 不是整数倍，因此无法转出

**Comment by geoexploring** [comment]
@jiangjiajun ，好的，谢谢解答！

**Comment by jiangjiajun** [comment]
@geoexploring  不客气，方便的话麻烦抽半分钟时间帮忙填下我们的用户问卷，帮忙我们了解大家的需求，改进飞桨模型的部署体验哈 https://iwenjuan.baidu.com/?code=r8hu2s

**Comment by geoexploring** [comment]
@jiangjiajun ，已填写，我转成ONNX主要是为了让OpenCV能直接调模型，因为OpenCV无法直接调用Paddle格式的模型
