### ISSUE TITLE
PP-structure to Onnx error 

### ISSUE THREAD

**Issue by iazdan** [PaddlePaddle/Paddle2ONNX#722]
**Please fill in the information below so that we can solve the problem quickly, Thanks !**

**Describe the bug**

I get the below error while converting the table recognition model. Does anyone know how to resolve this error?

**Informations (please complete the following information):**
 - Inference engine for deployment:
 - Why convert to onnx：
 - Paddle2ONNX Version:
 - Email/Wechat/Phone:

**Screenshots**

**Additional context**
Traceback (most recent call last):
File "bin/paddle2onnx", line 33, in
sys.exit(load_entry_point('paddle2onnx==0.9.3', 'console_scripts', 'paddle2onnx')())
File "/lib/python3.8/site-packages/paddle2onnx/command.py", line 273, in main
program2onnx(
File "/lib/python3.8/site-packages/paddle2onnx/command.py", line 200, in program2onnx
p2o.program2onnx(
File "lib/python3.8/site-packages/paddle2onnx/convert.py", line 95, in program2onnx
return export_onnx(
File "/paddle/lib/python3.8/site-packages/paddle2onnx/convert.py", line 35, in export_onnx
onnx_graph = ONNXGraph.build(paddle_graph, opset_version,
File "lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 323, in build
onnx_graph = ONNXGraph(
File "/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 85, in init
self.update_opset_version()
File "/lib/python3.8/site-packages/paddle2onnx/graph/onnx_graph.py", line 202, in update_opset_version
self.opset_version = OpMapper.get_recommend_opset_version(
File "/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 128, in get_recommend_opset_version
recommend_opset_version = OpMapper.check_support_status(
File "/lib/python3.8/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 174, in check_support_status
raise NotImplementedError(error_info)
NotImplementedError:
There's 6 ops are not supported yet
=========== tensor_array_to_tensor ===========
=========== while ===========
=========== write_to_array ===========
=========== select_input ===========
=========== lod_array_length ===========
=========== conditional_block ===========

**Comment by jiangjiajun** [comment]
It's not supported

**Comment by iazdan** [comment]
Will support for pp-structure to onnx model be added anytime soon? If not, could you please provide some guidelines on how to convert to onnx?

**Comment by Hossein-Chaghazardi** [comment]
I ran into the same problem. Will you please share a workaround?

**Comment by NBd-hub** [comment]
I got a same problem!!

**Comment by nissansz** [comment]
How to use onnx model for pp table model?

**Comment by Zheng-Bicheng** [comment]
* https://github.com/PaddlePaddle/Paddle2ONNX/pull/1324
