### ISSUE TITLE
ubuntu 20.04编译错误，使用cpu，cmake 3.18.0，python 3.8.10

### ISSUE THREAD

**Issue by memoryrobber** [PaddlePaddle/Paddle2ONNX#752]
编译最新的代码报错，环境为：ubuntu 20.04 ，使用cpu，cmake 3.18.0，python 3.8.10

报错如下，还需要其他的环境吗

-- Configuring incomplete, errors occurred!
See also "/home/ubuntu/paddle/Paddle2ONNX/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 299, in <module>
    setuptools.setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 144, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 67, in run
    self.do_egg_install()
  File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 109, in do_egg_install
    self.run_command('bdist_egg')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 172, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/usr/lib/python3/dist-packages/setuptools/command/bdist_egg.py", line 158, in call_command
    self.run_command(cmdname)
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3/dist-packages/setuptools/command/install_lib.py", line 23, in run
    self.build()
  File "/usr/lib/python3.8/distutils/command/install_lib.py", line 107, in build
    self.run_command('build_py')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 204, in run
    self.run_command('cmake_build')
  File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "setup.py", line 190, in run
    subprocess.check_call(cmake_args)
  File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/usr/include/python3.8', '-DPYTHON_EXECUTABLE=/usr/bin/python', '-DBUILD_PADDLE2ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=paddle2onnx', '-DPY_EXT_SUFFIX=.cpython-38-x86_64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '/home/ubuntu/paddle/Paddle2ONNX']' returned non-zero exit status 1.
[CMakeOutput.log](https://github.com/PaddlePaddle/Paddle2ONNX/files/8761865/CMakeOutput.log)

**Comment by jiangjiajun** [comment]
你好，你是在执行python setup.py时报的错吗，你可以直接pip install paddle2onnx安装

如若需要安装github源码，请参考[github源码安装](https://github.com/PaddlePaddle/Paddle2ONNX/blob/716626c40bba9ca5c5c56d6cd2e6d06a79320384/docs/zh/compile.md)

**Comment by memoryrobber** [comment]
> 你好，你是在执行python setup.py时报的错吗，你可以直接pip install paddle2onnx安装
> 
> 如若需要安装github源码，请参考[github源码安装](https://github.com/PaddlePaddle/Paddle2ONNX/blob/716626c40bba9ca5c5c56d6cd2e6d06a79320384/docs/zh/compile.md)

你好，感谢回复
 我是安装这个文档来编译的，之前都是顺利的，到最后一步失败了,
![image](https://user-images.githubusercontent.com/21274112/170019404-01b50a1b-0827-48bb-b80e-bdc9a2c297ca.png)

使用windows 10,vs2019编译也报错，parser.cc文件提示void* 参数错误，修改为char*可以编译，但是安装失败

**Comment by jiangjiajun** [comment]
拉一下最新的代码， 同时在export protobuf时，路径改下，先前的文档有问题。

另外现在pip install paddle2onnx有什么问题吗
<img width="780" alt="image" src="https://user-images.githubusercontent.com/19339784/170019970-99a738e4-3ddd-4124-84a5-9e9a78dbe944.png">

**Comment by memoryrobber** [comment]
谢谢回复，我试试拉一下代码，paddle2onnx 0.9.6 版本转换paddle detection faster rcnn模型总是失败，我想尝试一下编译最新的paddle2onnx来试试

**Comment by jiangjiajun** [comment]
0.9.6与Github上代码，在转RCNN模型时没有差别
