### ISSUE TITLE
onnx ShapeInferenceError when using onnxsim

### ISSUE THREAD

**Issue by MoonBunnyZZZ** [PaddlePaddle/Paddle2ONNX#826]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
1、paddle2onnx导出ppyoloe模型的onnx文件
2、使用onnxsim优化前述onnx模型，报错onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: Gather_12): [ShapeInferenceError] Inferred shape and existing shape differ in dimension 0: (1) vs (-1)
3、使用paddle2onnx.optimize指定input shape，无效

**更多信息 :**
 - 用于部署的推理引擎: onnx
 - 为什么需要转换为ONNX格式：部署
 - Paddle2ONNX版本: 0.9.8
 - 你的联系方式(Email/Wechat/Phone): 454047094@qq.com

**报错截图**
```
 onnxsim ppyoloe_crn_l_300e_coco.onnx ppyoloe_crn_l_300e_coco_sim.onnx                                                                                      
Simplifying...                                                                                                                                                
Traceback (most recent call last):                                                                                                                            
  File "/home/wx/miniconda3/envs/pd/bin/onnxsim", line 8, in <module>                                                                                         
    sys.exit(main())                                                                                                                                          
  File "/home/wx/miniconda3/envs/pd/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 444, in main                                                
    args.tensor_size_threshold,                                                                                                                               
  File "/home/wx/miniconda3/envs/pd/lib/python3.7/site-packages/onnxsim/onnx_simplifier.py", line 189, in simplify                                            
    tensor_size_threshold,                                                                                                                                    
onnx.onnx_cpp2py_export.shape_inference.InferenceError: [ShapeInferenceError] (op_type:Gather, node name: Gather_12): [ShapeInferenceError] Inferred shape and
 existing shape differ in dimension 0: (1) vs (-1)
```

**其他信息**

**Comment by jiangjiajun** [comment]
- 3、使用paddle2onnx.optimize制定input shape，无效

这个是怎么做的啊

**Comment by MoonBunnyZZZ** [comment]
> * 3、使用paddle2onnx.optimize制定input shape，无效
> 
> 这个是怎么做的啊
```
python -m paddle2onnx.optimize --input_model model.onnx \
                               --output_model new_model.onnx \
                               --input_shape_dict "{'x':[1,3,224,224]}"
```
如果这里不是指定input shape，那么是我理解有误

**Comment by MoonBunnyZZZ** [comment]
已解决，谢谢
