### ISSUE TITLE
paddle2onnx导出模型失败

### ISSUE THREAD

**Issue by chen-del** [PaddlePaddle/Paddle2ONNX#833]
PaddleSeg版本：PaddleSeg==2.6
PaddlePaddle版本：PaddlePaddle 2.1.0
操作系统信息：Linux
Python版本号：Python3.6.13
CUDA/cuDNN版本：CUDA11.2
Traceback (most recent call last):
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 119, in mapping
mapper_func(graph, node, **kw)
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/op_mapper/nn.py", line 186, in opset_1
node.input_shape('X', 0), node.output_shape('Out', 0)))
Exception: Cannot convert adaptive pool with input_size: (1, 24, 32, 32), output_size: (1, 24, 3, 3)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
File "/home/dell/anaconda3/envs/d2l/bin/paddle2onnx", line 8, in
sys.exit(main())
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/command.py", line 195, in main
input_shape_dict=input_shape_dict)
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/command.py", line 159, in program2onnx
operator_export_type=operator_export_type)
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/convert.py", line 88, in program2onnx
auto_update_opset)
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/convert.py", line 36, in export_onnx
auto_update_opset)
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/graph/onnx_graph.py", line 262, in build
onnx_graph.build_op_nodes(paddle_graph.node_map)
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/graph/onnx_graph.py", line 209, in build_op_nodes
OpMapper.mapping(self, node, self.operator_export_type)
File "/home/dell/anaconda3/envs/d2l/lib/python3.6/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 124, in mapping
node.outputs) + str(e))
Exception: Error happened when mapping node ['pool2d_3'] to onnx, which op_type is 'pool2d' with inputs: {'X': ['elementwise_add_0']} and outputs: {'Out': ['pool2d_11.tmp_0']}, specific error: Cannot convert adaptive pool with input_size: (1, 24, 32, 32), output_size: (1, 24, 3, 3)

导出出现了问题，使用所有的模型导出为onnx还是失败

**Comment by jiangjiajun** [comment]
@chen-del Hi, 请问你导出成ONNX是想用于什么目的啊

**Comment by chen-del** [comment]
@jiangjiajun   ，用于模型的推理部署

**Comment by chen-del** [comment]
@jiangjiajun  ，这个问题是不是主干设计错误，导致模型导出onnx失败

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/issues/813 原因同这个issue

**Comment by chen-del** [comment]
@jiangjiajun  这里的意思是我需要修改网络的AdaptivePooling2d 转为普通的conv2d算子嘛，但是据我所知道的onnx1.12已经支持导出AdaptivePooling2D了，我是需要修改bankbone嘛？

**Comment by jiangjiajun** [comment]
```
据我所知道的onnx1.12已经支持导出AdaptivePooling2D了
```
ONNX目前最新的标准里没有AdaptivePool的支持

当前如何导出，参考上面的issue，在输入Shape固定的情况下，部分场景可以将AdaptviePool转为普通的Pooling，所以你可以试下将这个Paddle模型的输入进行固定。这里提供了相应的工具帮忙固定Shape https://github.com/jiangjiajun/PaddleUtils/tree/main/paddle

**Comment by chen-del** [comment]
好的，谢谢
