### ISSUE TITLE
无法在 Python 3.10.6 中运行

### ISSUE THREAD

**Issue by KirinRyuuri** [PaddlePaddle/Paddle2ONNX#935]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
Paddle2ONNX 依赖 ONNX 1.9.0，不支持在 Python 3.10.6 中运行 [issue#3723](https://github.com/onnx/onnx/issues/3723)
手动升级 ONNX 到 1.12.0 之后无报错

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：
 - Paddle2ONNX版本:
   - Ubuntu 22.04 5.10.102.1-microsoft-standard-WSL2
   - Python 3.10.6
   - Paddle（nightly）```Version: 0.0.0```
   - Paddle2onnx ```Version: 0.9.2```
   - PaddleOCR ```release/2.6```
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
- 运行指令/Command Code：
```shell
paddle2onnx --model_dir ./inference/ch_PP-OCRv3_det_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/det_onnx/model.onnx \
--opset_version 10 \
--input_shape_dict="{'x':[-1,3,-1,-1]}" \
--enable_onnx_checker True
```

- 完整报错/Complete Error Message：
```python
/home/username/.local/lib/python3.10/site-packages/onnx/mapping.py:27: DeprecationWarning: `np.object` is a deprecated alias for the builtin `object`. To silence this warning, use `object` by itself. Doing this will not modify any behavior and is safe.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  int(TensorProto.STRING): np.dtype(np.object)
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
2022-10-27 13:46:43 [WARNING]   You are use develop version of paddlepaddle
I1027 13:46:43.140570  5001 interpretercore.cc:235] New Executor is Running.
2022-10-27 13:46:43 [WARNING]   The model is saved by paddlepaddle v2.2.2, but now your paddlepaddle is version of 0.0.0, this difference may cause error, it is recommend you reinstall a same version of paddlepaddle for this model
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/username/.local/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/command.py", line 218, in main
    program2onnx(
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/command.py", line 173, in program2onnx
    p2o.program2onnx(
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/convert.py", line 94, in program2onnx
    return export_onnx(
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/convert.py", line 35, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version,
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/graph/onnx_graph.py", line 328, in build    onnx_graph.build_parameters(paddle_graph.parameters)
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/graph/onnx_graph.py", line 184, in build_parameters
    node = helper.make_node(
  File "/home/username/.local/lib/python3.10/site-packages/onnx/helper.py", line 112, in make_node
    node.attribute.extend(
  File "/home/username/.local/lib/python3.10/site-packages/onnx/helper.py", line 113, in <genexpr>
    make_attribute(key, value)
  File "/home/username/.local/lib/python3.10/site-packages/onnx/helper.py", line 343, in make_attribute
    is_iterable = isinstance(value, collections.Iterable)
AttributeError: module 'collections' has no attribute 'Iterable'
```

**其他信息**

出现报错时 onnx 的版本为 ```Version: 1.9.0```
```shell
Name: onnx
Version: 1.9.0
Summary: Open Neural Network Exchange
Home-page: https://github.com/onnx/onnx
Author: ONNX
Author-email: onnx-technical-discuss@lists.lfai.foundation
License: Apache License v2.0
Location: /home/username/.local/lib/python3.10/site-packages
Requires: numpy, protobuf, six, typing-extensions
Required-by: paddle2onnx
```

使用 ```python -m pip install onnx --upgrade``` 更新 onnx 版本
```python
Defaulting to user installation because normal site-packages is not writeable
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: onnx in ./.local/lib/python3.10/site-packages (1.9.0)
Collecting onnx
  Downloading https://pypi.tuna.tsinghua.edu.cn/packages/53/b7/0a595a49bd5bc9af85498cd336f98cd1eaf4783f6eeed03908b12c5d11a4/onnx-1.12.0-cp310-cp310-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (13.1 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 13.1/13.1 MB 1.3 MB/s eta 0:00:00
Requirement already satisfied: typing-extensions>=3.6.2.1 in ./.local/lib/python3.10/site-packages (from onnx) (4.4.0)
Requirement already satisfied: numpy>=1.16.6 in ./.local/lib/python3.10/site-packages (from onnx) (1.23.4)
Requirement already satisfied: protobuf<=3.20.1,>=3.12.2 in ./.local/lib/python3.10/site-packages (from onnx) (3.20.0)
Installing collected packages: onnx
  Attempting uninstall: onnx
    Found existing installation: onnx 1.9.0
    Uninstalling onnx-1.9.0:
      Successfully uninstalled onnx-1.9.0
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
paddle2onnx 0.9.2 requires onnx<=1.9.0, but you have onnx 1.12.0 which is incompatible.
Successfully installed onnx-1.12.0
```

之后再运行相同的命令
```python
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
2022-10-27 13:48:37 [WARNING]   You are use develop version of paddlepaddle
I1027 13:48:37.315676  5086 interpretercore.cc:235] New Executor is Running.
2022-10-27 13:48:37 [WARNING]   The model is saved by paddlepaddle v2.2.2, but now your paddlepaddle is version of 0.0.0, this difference may cause error, it is recommend you reinstall a same version of paddlepaddle for this model
2022-10-27 13:48:37 [INFO]      ONNX model generated is valid.
2022-10-27 13:48:37 [INFO]      ONNX model saved in ./inference/det_onnx/model.onnx
```

---

因为 PaddleOCR 本身不支持 Ubuntu 22.04 的 GCC 11.2.0 ，所以 PaddleOCR 使用的是 nightly （看 [issue#44571](https://github.com/PaddlePaddle/Paddle/issues/44571) [pr#45351](https://github.com/PaddlePaddle/Paddle/pull/45351)已经在 rc 中修复了。
但是 Paddle2ONNX 依赖的 ONNX 1.9.0 不支持 Python 3.10.6 [issue#3723](https://github.com/onnx/onnx/issues/3723) ，所以在更新 ONNX 版本到 1.12.0 之后可以正常导出。

**Comment by KirinRyuuri** [comment]
后来排查了一下，问题确实出现在 Python 3.10.6 上，Python 3.10.6 从 pypi 上下载的包版本为 0.9.6，实际上最新版本应该是 1.0.1

重装 Python 3.9.15 和 Paddle2ONNX 1.0.1 之后问题同样可以解决。

**Comment by KirinRyuuri** [comment]
如果使用 Python 3.10.6 进行转换，命令如下
```shell
paddle2onnx --model_dir ./inference/ch_PP-OCRv3_rec_infer \
--model_filename inference.pdmodel \
--params_filename inference.pdiparams \
--save_file ./inference/rec_onnx/model.onnx \
--enable_onnx_checker True
```


报错信息如下
```python
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:47: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  np.bool: core.VarDesc.VarType.BOOL,
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:48: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.FP32: np.float,
/home/username/.local/lib/python3.10/site-packages/paddle2onnx/constant/dtypes.py:53: DeprecationWarning: `np.bool` is a deprecated alias for the builtin `bool`. To silence this warning, use `bool` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.bool_` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  core.VarDesc.VarType.BOOL: np.bool
2022-10-27 17:31:32 [WARNING]   You are use develop version of paddlepaddle
I1027 17:31:33.009392 14354 interpretercore.cc:235] New Executor is Running.
/usr/lib/python3/dist-packages/apport/report.py:13: DeprecationWarning: the imp module is deprecated in favour of importlib and slated for removal in Python 3.12; see the module's documentation for alternative uses
  import fnmatch, glob, traceback, errno, sys, atexit, locale, imp, stat
Traceback (most recent call last):
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 119, in mapping
    mapper_func(graph, node, **kw)
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/op_mapper/nn.py", line 548, in opset_7
    if isinstance(normalized_shape, collections.Iterable):
AttributeError: module 'collections' has no attribute 'Iterable'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/username/.local/bin/paddle2onnx", line 8, in <module>
    sys.exit(main())
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/command.py", line 218, in main
    program2onnx(
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/command.py", line 173, in program2onnx
    p2o.program2onnx(
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/convert.py", line 94, in program2onnx
    return export_onnx(
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/convert.py", line 35, in export_onnx
    onnx_graph = ONNXGraph.build(paddle_graph, opset_version,
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/graph/onnx_graph.py", line 331, in build
    onnx_graph.build_op_nodes(paddle_graph.node_map)
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/graph/onnx_graph.py", line 209, in build_op_nodes
    OpMapper.mapping(self, node, self.operator_export_type)
  File "/home/username/.local/lib/python3.10/site-packages/paddle2onnx/op_mapper/op_mapper.py", line 121, in mapping
    raise Exception(
Exception: Error happened when mapping node ['layer_norm_0'] to onnx, which op_type is 'layer_norm' with inputs: {'Bias': ['layer_norm_5.b_0'], 'Scale': ['layer_norm_5.w_0'], 'X': ['transpose_9.tmp_0']} and outputs: {'Mean': ['layer_norm_15.tmp_0'], 'Variance': ['layer_norm_15.tmp_1'], 'Y': ['layer_norm_15.tmp_2']}, specific error: module 'collections' has no attribute 'Iterable'
```

**Comment by jiangjiajun** [comment]
最新版Paddle2ONNX，暂时还没有支持3.10（由于编译环境还没升级，所以只编译到了3.9）

https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/compile.md 当前你可以参照这个文档，自行编译一个3.10下的paddle2onnx
