### ISSUE TITLE
jetson安装Paddle2ONNX失败

### ISSUE THREAD

**Issue by Biaocsu** [PaddlePaddle/Paddle2ONNX#946]
``**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
请在此处详细的描述报错信息

**更多信息 :**
 - 用于部署的推理引擎:
 - 为什么需要转换为ONNX格式：系统为jetson arrch 64架构，无法安装PaddleOCR，因此尝试将模型转换为onnx格式，看是否该方式模型是否可以在该机器预测运行
 - Paddle2ONNX版本:
 - 你的联系方式(Email/Wechat/Phone):17762693896

**报错截图**

**其他信息**
`(python36) nvidia@nvidia-desktop:~/project/Paddle2ONNX-develop$ python setup.py install
fatal: 不是一个 git 仓库（或者任何父目录）：.git
/home/nvidia/.local/lib/python3.6/site-packages/setuptools/dist.py:493: UserWarning: Normalizing '1.0.2rc' to '1.0.2rc0'
  warnings.warn(tmpl.format(**locals()))
running install
/home/nvidia/.local/lib/python3.6/site-packages/setuptools/command/install.py:37: SetuptoolsDeprecationWarning: setup.py install is deprecated. Use build and pip and other standards-based tools.
  setuptools.SetuptoolsDeprecationWarning,
/home/nvidia/.local/lib/python3.6/site-packages/setuptools/command/easy_install.py:159: EasyInstallDeprecationWarning: easy_install command is deprecated. Use build and pip and other standards-based tools.
  EasyInstallDeprecationWarning,
running bdist_egg
running egg_info
creating paddle2onnx.egg-info
writing paddle2onnx.egg-info/PKG-INFO
writing dependency_links to paddle2onnx.egg-info/dependency_links.txt
writing entry points to paddle2onnx.egg-info/entry_points.txt
writing requirements to paddle2onnx.egg-info/requires.txt
writing top-level names to paddle2onnx.egg-info/top_level.txt
writing manifest file 'paddle2onnx.egg-info/SOURCES.txt'
reading manifest file 'paddle2onnx.egg-info/SOURCES.txt'
adding license file 'LICENSE'
writing manifest file 'paddle2onnx.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-aarch64/egg
running install_lib
running build_py
running create_version
running cmake_build
-- The C compiler identification is GNU 7.5.0
-- The CXX compiler identification is GNU 7.5.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
CMake Error at CMakeLists.txt:2 (CMAKE_MINIMUM_REQUIRED):
  CMake 3.16 or higher is required.  You are running version 3.10.2

-- Configuring incomplete, errors occurred!
See also "/home/nvidia/project/Paddle2ONNX-develop/.setuptools-cmake-build/CMakeFiles/CMakeOutput.log".
Traceback (most recent call last):
  File "setup.py", line 320, in <module>
    entry_points={'console_scripts': ['paddle2onnx=paddle2onnx.command:main']})
  File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/dist.py", line 955, in run_commands
    self.run_command(cmd)
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 74, in run
    self.do_egg_install()
  File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools/command/install.py", line 116, in do_egg_install
    self.run_command('bdist_egg')
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 164, in run
    cmd = self.call_command('install_lib', warn_dir=0)
  File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools/command/bdist_egg.py", line 150, in call_command
    self.run_command(cmdname)
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "/home/nvidia/.local/lib/python3.6/site-packages/setuptools/command/install_lib.py", line 11, in run
    self.build()
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/command/install_lib.py", line 105, in build
    self.run_command('build_py')
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 204, in run
    self.run_command('cmake_build')
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/distutils/dist.py", line 974, in run_command
    cmd_obj.run()
  File "setup.py", line 190, in run
    subprocess.check_call(cmake_args)
  File "/home/nvidia/archiconda3/envs/python36/lib/python3.6/subprocess.py", line 311, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['/usr/bin/cmake', '-DPYTHON_INCLUDE_DIR=/home/nvidia/archiconda3/envs/python36/include/python3.6m', '-DPYTHON_EXECUTABLE=/home/nvidia/archiconda3/envs/python36/bin/python', '-DBUILD_PADDLE2ONNX_PYTHON=ON', '-DCMAKE_EXPORT_COMPILE_COMMANDS=ON', '-DONNX_NAMESPACE=paddle2onnx', '-DPY_EXT_SUFFIX=.cpython-36m-aarch64-linux-gnu.so', '-DCMAKE_BUILD_TYPE=Release', '/home/nvidia/project/Paddle2ONNX-develop']' returned non-zero exit status 1.`

**Comment by yeliang2258** [comment]
看报错是你的cmake版本太低，我们要求CMake 3.16 以上。另外，我认为模型转换可以在普通的X86 linux上完成，然后将转换后的ONNX模型放到部署机器上进行部署

**Comment by Biaocsu** [comment]
@yeliang2258 是的。我已经在百度飞桨aistudio上完成了模型转换，模型已经是onnx格式。现在需要在jetson机器上运行，但是运行时好像是需要安装paddle2onnx吧？难道我理解错了，不需要安装，直接运行？

**Comment by yeliang2258** [comment]
运行的时候应该要装的是ONNXRuntime吧，如果还是需要装Paddle2ONNX的话，你可以升级一下你的Cmake，然后再试试

**Comment by Biaocsu** [comment]
好的，多谢
