### ISSUE TITLE
Pdmodel转onnx版本问题

### ISSUE THREAD

**Issue by sunmooncode** [PaddlePaddle/Paddle2ONNX#966]
**请将下面信息填写完整，便于我们快速解决问题，谢谢！**

**问题描述**
在pdmodel转onnx的时候会出现版本问题，高版本（onnx==1.12.0）转换不会出现下面报错，但由于通过高版本转换的ONNX模型在转换rknn的时候会同样出现以下错误。所以只能降低onnx版本来转换pdmodel，但是低版本（onnx==1.8.0）无法转换成功，会出现以下错误。

**更多信息 :**
 - 用于部署的推理引擎:RK3566
 - 为什么需要转换为ONNX格式：在npu端部署
 - Paddle2ONNX版本:1.0.1
 - 你的联系方式(Email/Wechat/Phone):

**报错截图**
```
Traceback (most recent call last):
  File "tools/model/export_onnx.py", line 121, in <module>
    export_onnx(args)
  File "tools/model/export_onnx.py", line 111, in export_onnx
    onnx_out = check_and_run_onnx(onnx_model_path, input_data)
  File "tools/model/export_onnx.py", line 72, in check_and_run_onnx
    onnx.checker.check_model(onnx_model)
  File "/home/anaconda3/envs/ppseg/lib/python3.8/site-packages/onnx/checker.py", line 102, in check_model
    C.check_model(protobuf_string)
onnx.onnx_cpp2py_export.checker.ValidationError: Your model ir_version is higher than the checker's.
```

**其他信息**

**Comment by jiangjiajun** [comment]
https://github.com/PaddlePaddle/Paddle2ONNX/blob/develop/docs/zh/FAQ.md

参考这里第三个问题解决方式
